<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php if ($this->mode == 'mail'): ?>
<?php foreach ($this->rows as $row): ?>
<?php echo $row['firstname'] . ' ' . $row['lastname'] . ' <' . $row['email'] . ">\n"; ?>
<?php endforeach; ?>
<?php elseif ($this->mode == 'affiliation'): ?>
<?php foreach ($this->rows as $row): ?>
<?php echo $row['lastname'] . ', ' . $row['firstname'] . ' (' . $row['affiliation'] . ")\n"; ?>
<?php endforeach; ?>
<?php else: ?>
<?php foreach ($this->rows as $row): ?>
<?php echo $row['lastname'] . ', ' . $row['firstname'] . "\n";  ?>
<?php endforeach; ?>
<?php endif; ?>