<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php
if (in_array($this->mode, array('csv','excel'))) {
    $values = array();
    foreach (array_merge($this->keys, $this->detailKeys) as $key) {
        $values[] = '"' . ucfirst($this->escape($key)) . '"';
    }
    foreach ($this->contributionTypes as $contibutionType) {
        $values[] = '"' . ucfirst($contibutionType) . ' title"';
        $values[] = '"' . ucfirst($contibutionType) . ' abstract"';
    }
    if ($this->mode == 'csv') {
        echo implode(',',$values) . "\n";
    } else {
        echo implode(';',$values) . "\n";
    }
}

foreach ($this->rows as $row) {
    if ($this->mode == 'mail') {
        echo $row['firstname'] . ' ' . $row['lastname'] . ' <' . $row['email'] . ">\n";
    } else if ($this->mode == 'affiliation') {
        echo $row['lastname'] . ', ' . $row['firstname'] . ' (' . $row['affiliation'] . ")\n";
    } else if ($this->mode == 'csv' || $this->mode == 'excel') {
        $values = array();
        foreach ($this->keys as $key) {
            $values[] = '"' . $this->escape($row[$key]) . '"';
        }
        foreach ($row['details'] as $key => $value) {
            if (is_array($value)) {
                $values[] = '"' . $this->escape(implode(', ',$value)) . '"';
            } else if (empty($value)) {
                $values[] = '""';
            } else {
                $values[] = '"' . $this->escape($value) . '"';
            }
        }
        foreach ($this->contributionTypes as $contributionType) {
            if (isset($row['contributions'][$contributionType])) {
                $values[] = '"' . $this->escape($row['contributions'][$contributionType]['title']) . '"';
                $values[] = '"' . $this->escape(trim(preg_replace('/\s+/', ' ', $row['contributions'][$contributionType]['abstract']))) . '"';
            } else {
                $values[] = '""';
                $values[] = '""';
            }
        }
        if ($this->mode == 'csv') {
            echo implode(',',$values) . "\n";
        } else if ($this->mode == 'excel') {
            echo implode(';',$values) . "\n";
        }
    } else {
        echo $row['lastname'] . ', ' . $row['firstname'] . "\n";
    }
}
?>
