<?php

/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <?php
    if (isset($this->meeting)){
        echo "<h2>Participants for {$this->escape($this->meeting['title'])}</h2>";
        $cols = "/meetings/participants/cols?meetingId={$this->meeting['id']}";
        $rows = "/meetings/participants/rows?meetingId={$this->meeting['id']}";
    } else {
        echo "<h2>Participants for all meetings</h2>";
        $cols = "/meetings/participants/cols";
        $rows = "/meetings/participants/rows";
    }
    ?>

    <div daiquiri-table data-cols="<?php echo $cols; ?>" data-rows="<?php echo $rows; ?>"></div>

    <div class="row">
        <div class="span6">
            <div class="daiquiri-widget">
                <ul class="unstyled">
                    <li>Export names:
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'all',
                        'href' => '/meetings/' . $this->slug . '/participants/export/',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export',
                        'append' => ',&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'accepted',
                        'href' => '/meetings/' . $this->slug . '/participants/export/status/accepted',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export',
                        'append' => ',&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'rejected',
                        'href' => '/meetings/' . $this->slug . '/participants/export/status/rejected',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export'
                    ));
                    ?>
                    </li>

                    <li>Export names and emails:
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'all',
                        'href' => '/meetings/' . $this->slug . '/participants/export/mode/mail',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export',
                        'append' => ',&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'accepted',
                        'href' => '/meetings/' . $this->slug . '/participants/export/mode/mail/status/accepted',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export',
                        'append' => ',&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'rejected',
                        'href' => '/meetings/' . $this->slug . '/participants/export/mode/mail/status/rejected',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export'
                    ));
                    ?>
                    </li>

                    <li>Export names and affiliations:
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'all',
                        'href' => '/meetings/' . $this->slug . '/participants/export/mode/affiliation',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export',
                        'append' => ',&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'accepted',
                        'href' => '/meetings/' . $this->slug . '/participants/export/mode/affiliation/status/accepted',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export',
                        'append' => ',&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'rejected',
                        'href' => '/meetings/' . $this->slug . '/participants/export/mode/affiliation/status/rejected',
                        'target' => 'blank',
                        'resource' => 'Meetings_Model_Participants',
                        'permission' => 'export'
                    ));
                    ?>
                    </li>
                </ul>
            </div>
        </div>
        <div class="span3">
            <div class="daiquiri-widget">
            <?php
            echo $this->internalLink(array(
                'text' => 'Create new participant',
                'href' => '/meetings/' . $this->slug . '/participants/create/',
                'prepend' => '<p>',
                'append' => '</p>',
                'ng-click' => 'fetchHtml($event)'));
            ?>
            </div>
        </div>

        <div class="span3 pull-right">
            <div class="daiquiri-widget">
                <?php
                echo $this->internalLink(array(
                    'text' => 'Back to meetings',
                    'href' => '/meetings/meetings/',
                    'prepend' => '<p>',
                    'append' => '</p>'));
                    ?>
            </div>
        </div>
    </div>

    <div daiquiri-modal></div>
</div>
