<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<?php
$id = $this->row['id'];
unset($this->row['meeting_id']);
unset($this->row['status_id']);
?>

<div class="main">
    <h2>Participant <?php echo $this->escape($this->row['firstname'] . ' ' . $this->row['lastname']); ?></h2>

    <h4>Participant information</h4>

    <dl class="dl-horizontal">
        <?php
        foreach (array('id','firstname','lastname','affiliation','arrival','email') as $key) {
            echo "<dt>{$this->escape(ucfirst($key))}</dt>";
            if (!empty($this->row[$key])) {
                echo "<dd>{$this->escape($this->row[$key])}</dd>";
            } else {
                echo "<dd>&nbsp;</dd>";
            }
        }
        ?>
    </dl>

    <h4>Contributions</h4>

    <?php if (!empty($this->row['contributions'])): ?>
    <dl class="dl-horizontal">
        <?php foreach ($this->row['contributions'] as $key => $contribution): ?>
        <dt><?php echo $this->escape(ucfirst($key)); ?></dt>
        <dd>
            <strong><?php echo $this->escape($contribution['title']); ?></strong>
            <?php echo $this->escape($contribution['abstract']); ?>
        </dd>
        <?php endforeach; ?>
    </dl>
    <?php else: ?>
        <p>none</p>
    <?php endif; ?>
</div>
