<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2><?php echo $this->escape($this->row['lastname'] . ', ' . $this->row['firstname']); ?></h2>

    <table class="table table-bordered">
        <tbody>
            <?php foreach ($this->row as $key => $value): ?>
                <?php if (substr($key, -strlen('_id')) !== '_id'): ?>
                <tr>
                    <td class="onehundredeighty"><?php echo ucfirst(str_replace('_',' ',$this->escape($key))); ?></td>
                    <td>
                        <?php if (is_array($value)): ?>
                            <?php foreach($value as $contribution): ?>
                                <table class="table table-bordered">
                                    <tbody>
                                        <?php foreach($contribution as $k => $v): ?>
                                            <tr>
                                                <td class="onehundredeighty"><?php echo ucfirst($this->escape($k)); ?></td>
                                                <td><?php echo $this->escape($v); ?></td>
                                            </tr>
                                        <?php endforeach; ?> 
                                    </tbody>
                                </table>
                            <?php endforeach; ?>  
                        <?php else: ?>
                            <?php echo $this->escape($value); ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endif; ?>
            <?php endforeach; ?>  
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => 'Back',
        'class' => 'daiquiri-modal-close',
        'href' => $this->redirect,
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
