<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <h2><?php echo $this->escape($this->title); ?></h2>

    <table class="table table-bordered">
        <tbody>
            <?php foreach ($this->data as $key => $value): ?>
                <tr>
                    <td class="onehundredeighty"><?php echo ucfirst($this->escape($key)); ?></td>
                    <td>
                        <?php if (is_array($value)): ?>


                            <?php foreach($value as $contribution): ?>
                                <table class="table table-bordered">
                                    <tbody>
                                        <?php foreach($contribution as $k => $v): ?>
                                            <tr>
                                                <td class="onehundredeighty"><?php echo ucfirst($this->escape($k)); ?></td>
                                                <td><?php echo $this->escape($v); ?></td>
                                            </tr>
                                        <?php endforeach; ?> 
                                    </tbody>
                                </table>
                            <?php endforeach; ?>  
                        <?php else: ?>
                            <?php echo $this->escape($value); ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>  
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => 'Back',
        'href' => $this->redirect,
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
