<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Examples</h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Name</th>
                <th>Published for</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $example): ?>
                <tr>
                    <td><?php echo $this->escape($example['name']); ?></td>
                    <td><?php echo $this->escape($example['publication_role']); ?></td>
                    <td>
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Edit',
                            'href' => '/query/examples/update/id/' . $this->escape($example['id']),
                            'resource' => 'Query_Model_Examples',
                            'permission' => 'update'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/query/examples/delete/id/' . $this->escape($example['id']),
                            'resource' => 'Query_Model_Examples',
                            'permission' => 'delete',
                            'prepend' => '&nbsp;'));
                        ?>
                    </td>
                </tr>
            <?php endforeach;
            ?>
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => 'Create new example',
        'href' => '/query/examples/create',
        'resource' => 'Query_Model_Examples',
        'permission' => 'create',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Export to init.php syntax',
        'href' => '/query/examples/export',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Back to Administration',
        'href' => '/admin/',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
