<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <h2>Examples</h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Name</th>
                <th>Published for</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $example): ?>
                <tr>
                    <td><?php echo $this->escape($example['name']); ?></td>
                    <td><?php echo $this->escape($example['publication_role']); ?></td>
                    <td>
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Edit',
                            'href' => '/query/examples/update/id/' . $this->escape($example['id']),
                            'resource' => 'Query_Model_Examples',
                            'permission' => 'update'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/query/examples/delete/id/' . $this->escape($example['id']),
                            'resource' => 'Query_Model_Examples',
                            'permission' => 'delete',
                            'prepend' => '&nbsp;'));
                        ?>
                    </td>
                </tr>
            <?php endforeach;
            ?>
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => 'Create new example',
        'href' => '/query/examples/create',
        'resource' => 'Query_Model_Examples',
        'permission' => 'create',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Export to init.php syntax',
        'href' => '/query/examples/export',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Back to Administration',
        'href' => '/admin/',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
