<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<h2>Administration</h2>

<ul class="nav nav-tabs nav-stacked span9">
    <?php
    echo $this->internalLink(array(
        'text' => 'Configuration overview (view and update configuration parameters)',
        'href' => '/config/entries',
        'resource' => 'Config_Model_Entries',
        'permission' => 'index',
        'prepend' => '<li>',
        'append' => '</li>'));
    echo $this->internalLink(array(
        'text' => 'Mail templates configuration (view and update mail templates)',
        'href' => '/config/templates',
        'resource' => 'Config_Model_Templates',
        'permission' => 'index',
        'prepend' => '<li>',
        'append' => '</li>'));
    echo $this->internalLink(array(
        'text' => 'User management (view and manage user registred with the system)',
        'href' => '/auth/user',
        'resource' => 'Auth_Model_User',
        'permission' => 'rows',
        'prepend' => '<li>',
        'append' => '</li>'));
    echo $this->internalLink(array(
        'text' => 'Database management (view and manage tables)',
        'href' => '/data',
        'resource' => 'Data_Model_Databases',
        'permission' => 'show',
        'prepend' => '<li>',
        'append' => '</li>'));
    echo $this->internalLink(array(
        'text' => 'Sessions management (view and destroy current user sessions)',
        'href' => '/auth/sessions',
        'resource' => 'Auth_Model_Sessions',
        'permission' => 'rows',
        'prepend' => '<li>',
        'append' => '</li>'));
    echo $this->internalLink(array(
        'text' => 'Contact messages (view and respond to contact messages)',
        'href' => '/contact/messages',
        'resource' => 'Contact_Model_Messages',
        'permission' => 'rows',
        'prepend' => '<li>',
        'append' => '</li>'));
    echo $this->internalLink(array(
        'text' => 'Query jobs (view and manage database query jobs)',
        'href' => '/query/jobs',
        'resource' => 'Query_Model_Jobs',
        'permission' => 'rows',
        'prepend' => '<li>',
        'append' => '</li>'));
    ?>
</ul>