---

- name: Daiquiri setup (CentOS)
  hosts: all
  remote_user: root
  tasks:

  # install packages

  - name: install the mysql from a the mysql repo (CentOS 6)
    yum: name=http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm state=present
    when: ansible_distribution_major_version == "6"

  - name: install the mysql from a the mysql repo (CentOS 7)
    yum: name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm state=present
    when: ansible_distribution_major_version == "7"

  - name: packages are installed
    yum: name={{item}} state=present
    with_items:
    - gcc
    - gcc-c++
    - httpd
    - mod_xsendfile
    - cmake
    - git
    - php
    - php-devel
    - php-mysql
    - php-gd
    - php-process
    - php-pear-HTTP-Request2
    - mysql-community-client
    - mysql-community-server
    - mysql-community-devel

  # configure apache

  - name: copy vhosts.conf file
    copy: src=../../apache/centos{{ansible_distribution_major_version}}.conf dest=/etc/httpd/conf.d/vhosts.conf force=no

  # php config

  - name: extend php execution time
    lineinfile: dest=/etc/php.ini regexp=^max_execution_time line="max_execution_time = 600"

  - name: extend php POST max size
    lineinfile: dest=/etc/php.ini regexp=^post_max_size line="post_max_size = 32M"

  - name: extend php max upload filesize
    lineinfile: dest=/etc/php.ini regexp=^upload_max_filesize line="upload_max_filesize = 32M"

  # start services

  - name: start httpd
    service: name=httpd state=started enabled=yes

  - name: start MySQL
    service: name=mysqld state=started enabled=yes

  # directories

  - name: create src directory
    file: path=/srv/src state=directory

  - name: create captcha directory
    file: path=/srv/captcha state=directory owner=apache group=apache

  - name: create download directory
    file: path=/srv/download state=directory owner=apache group=apache

  - name: create navigation directory
    file: path=/srv/navigation state=directory owner=apache group=apache

  - name: create log directory
    file: path=/srv/log state=directory owner=apache group=apache

  # obtain daiquiri

  - name: clone the daiquiri repository
    git: repo=https://github.com/jochenklar/daiquiri.git dest=/srv/daiquiri update=no
