---

- name: Daiquiri setup - gearman (CentOS)
  hosts: all
  remote_user: root
  tasks:

  - name: packages for gearman are installed
    yum: name={{item}} state=present
    with_items:
    - gearmand
    - libgearman
    - libgearman-devel
    - php-pecl-gearman
