<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php foreach ($this->data as $database): ?>
    <table class='table table-bordered'>
        <?php foreach ($database as $dbKey => $dbValue): ?>
            <tr>
                <td class="onehundredtwenty"><?php echo ucfirst($this->escape($dbKey)); ?></td>
                <td>
                    <?php if (is_array($dbValue)): ?>
                        <?php foreach ($dbValue as $table): ?>
                            <div class="accordion" id="accordion-table-<?php echo $this->escape($table['id']); ?>">
                                <div class="accordion-group">
                                    <div class="accordion-heading">
                                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse-table-<?php echo $this->escape($table['id']); ?>">
                                            <?php echo $this->escape($table['name']); ?>
                                        </a>
                                    </div>
                                    <div id="collapse-table-<?php echo $this->escape($table['id']); ?>" class="accordion-body collapse">
                                        <div class="accordion-inner">
                                            <table class='table table-bordered'>
                                                <?php foreach ($table as $tableKey => $tableValue): ?>
                                                    <tr>
                                                        <td class="onehundredtwenty"><?php echo ucfirst($this->escape($tableKey)); ?></td>
                                                        <td>
                                                            <?php if (is_array($tableValue)): ?>
                                                                <?php foreach ($tableValue as $col): ?>
                                                                    <div class="accordion" id="accordion-col-<?php echo $this->escape($col['id']); ?>">
                                                                        <div class="accordion-group">
                                                                            <div class="accordion-heading">
                                                                                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse-col-<?php echo $col['id'] ?>">
                                                                                    <?php echo $this->escape($col['name']); ?>
                                                                                </a>
                                                                            </div>
                                                                            <div id="collapse-col-<?php echo $this->escape($col['id']); ?>" class="accordion-body collapse">
                                                                                <div class="accordion-inner">
                                                                                    <table class='table table-bordered'>
                                                                                        <?php foreach ($col as $colKey => $colValue): ?>
                                                                                            <tr>
                                                                                                <td class="onehundredtwenty"><?php echo $this->escape($colKey); ?></td>
                                                                                                <td><?php echo $this->escape($colValue); ?></td>
                                                                                            </tr>
                                                                                        <?php endforeach; ?>
                                                                                    </table>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    <?php endforeach; ?>
                                                                <?php else: ?>
                                                                    <?php echo $this->escape($tableValue); ?>
                                                                <?php endif; ?>
                                                        </td>
                                                    </tr>   
                                                <?php endforeach; ?>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <?php echo $this->escape($dbValue); ?>
                        <?php endif; ?>
                </td>
            </tr>   
        <?php endforeach; ?>
    </table>
<?php endforeach; ?>
