<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Databases</h2>

    <?php foreach ($this->databases as $database): ?>

    <h6><?php echo $this->escape($database['name']); ?></h6>

    <dl class="dl-horizontal">
        <?php foreach ($database as $dbKey => $dbValue): ?>
        <?php if ($dbKey !== 'tables'): ?>
        <dt><?php echo $this->escape(ucfirst($dbKey)); ?></dt>
        <dd><?php echo (empty($dbValue) ? '&nbsp' : $this->escape($dbValue)) ?></dd>
        <?php endif; ?>
        <?php endforeach; ?>
    </dl>

    <?php foreach ($database['tables'] as $table): ?>

    <h6><?php echo $this->escape($database['name'] . '.' . $table['name']); ?></h6>

    <dl class="dl-horizontal">
        <?php foreach ($table as $tableKey => $tableValue): ?>
        <?php if ($tableKey !== 'columns'): ?>
        <dt><?php echo $this->escape(ucfirst($tableKey)); ?></dt>
        <dd><?php echo (empty($tableValue) ? '&nbsp' : $this->escape($tableValue)) ?></dd>
        <?php endif; ?>
        <?php endforeach; ?>
    </dl>

    <?php foreach ($table['columns'] as $column): ?>

    <h6><?php echo $this->escape($database['name'] . '.' . $table['name'] . '.' . $column['name']); ?></h6>

    <dl class="dl-horizontal">
        <?php foreach ($column as $columnKey => $columnValue): ?>
        <dt><?php echo $this->escape(ucfirst($columnKey)); ?></dt>
        <dd><?php echo (empty($columnValue) ? '&nbsp' : $this->escape($columnValue)) ?></dd>
        <?php endforeach; ?>
    </dl>

    <?php endforeach; ?>
    <?php endforeach; ?>
    <?php endforeach; ?>
</div>
