<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php if ($this->status === 'ok'): ?>
    <h4>Database details</h4>

    <table class='table table-bordered'>
        <tr>
            <td class="onehundredtwenty">Database name</td>
            <td>
                <?php echo $this->escape($this->data['name']); ?>
            </td>
        </tr>   
        <tr>
            <td class="onehundredtwenty">Description</td>
            <td>
                <?php echo $this->escape($this->data['description']); ?>
            </td>
        </tr>   
    </table>

    <?php if(array_key_exists("tables", $this->data) && !empty($this->data['tables'])): ?>
        <?php foreach ($this->data['tables'] as $table): ?>
            <h5>Table details</h5>

            <table class='table table-bordered'>
                <tr>
                    <td class="onehundredtwenty">Database name</td>
                    <td>
                        <?php echo $this->escape($this->data['name']); ?>
                    </td>
                </tr>   
                <tr>
                    <td class="onehundredtwenty">Table name</td>
                    <td>
                        <?php echo $this->escape($table['name']); ?>
                    </td>
                </tr>   
                <tr>
                    <td class="onehundredtwenty">Description</td>
                    <td>
                        <?php echo $this->escape($table['description']); ?>
                    </td>
                </tr>   
            </table>

            <?php if(array_key_exists("columns", $table) && !empty($table['columns'])): ?>
                <h6>Column details</h6>

                <table class='table table-bordered'>
                    <tr>
                        <td class="onehundredtwenty">Column</td>
                        <td class="eighty">Type</td>
                        <td class="onehundredtwenty">UCD</td>
                        <td class="onehundred">Unit</td>
                        <td>Description</td>
                    </tr>   

                    <?php foreach ($table['columns'] as $cols): ?>
                        <tr>
                            <td class="onehundredtwenty">
                                <?php echo $this->escape($cols['name']); ?>
                            </td>
                            <td class="eighty">
                                <?php echo $this->escape($cols['type']); ?>
                            </td>
                            <td class="onehundredtwenty">
                                <?php echo $this->escape($cols['ucd']); ?>
                            </td>
                            <td class="onehundred">
                                <?php echo $this->escape($cols['unit']); ?>
                            </td>
                            <td>
                                <?php echo $this->escape($cols['description']); ?>
                            </td>
                        </tr>   
                    <?php endforeach; ?>
                </table>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>    
<?php else: ?>
<h5>Error retrieving database information</h5>
<?php endif; ?>