<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <div class="row">
            <div class="span9">
                <div class="box">
                    <p>
                        <span class="meta">DATABASE</span>
                        <strong><?php echo $this->escape($this->row['name']); ?></strong>
                    </p>
                </div>
                <table class='table table-bordered'>
                    <?php foreach($this->row as $key => $value): ?>
                    <?php if ($key !== 'tables'): ?>
                    <tr>
                        <td class="onehundredtwenty"><?php echo $this->escape($key); ?></td>
                        <td>
                            <?php echo $this->escape($value); ?>
                        </td>
                    </tr>
                    <?php endif; ?>
                    <?php endforeach ?>
                    <?php if (!empty($this->row['tables'])): ?>
                    <tr>
                        <td class="onehundredtwenty">Tables</td>
                        <td>
                            <ul class="unstyled">
                                <?php foreach($this->row['tables'] as $table): ?>
                                <li>
                                    <div><?php echo $this->escape($table['name']); ?></div>
                                    <ul>
                                        <?php foreach($table['columns'] as $column): ?>
                                        <li><?php echo $this->escape($column['name']); ?></li>
                                        <?php endforeach; ?>
                                    </ul>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </td>
                    </tr>
                    <?php endif; ?>
                </table>
            </div>
            <div class="span3">
                <div class="box">
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'Update this database entry',
                        'href' => '/data/databases/update?id=' . $this->escape($this->row['id']),
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Delete this database entry',
                        'href' => '/data/databases/delete?id=' . $this->escape($this->row['id']),
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    ?>
                </div>
                <div class="box">
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'Create new database entry',
                        'href' => '/data/databases/create',
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new table entry',
                        'href' => '/data/tables/create?databaseId=' . $this->escape($this->row['id']),
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new column entry',
                        'href' => '/data/columns/create',
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new function entry',
                        'href' => '/data/functions/create',
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    ?>
                </div>
            </div>
        </div>
    <?php else: ?>
    <h5>Error retrieving database information</h5>
    <?php endif; ?>
</div>
