<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <h2>Mail templates</h2>

    <table class="table table-condensed table-bordered">
        <thead>
            <tr>
                <th style="width: 30%">Template</th>
                <th style="width: 65%">Subject</th>
                <th style="width: 5%">Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <td style="width: 30%"><?php echo $this->escape($row['template']); ?></td>
                    <td style="width: 65%"><?php echo $this->escape($row['subject']); ?></td>
                    <td style="width: 5%">
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Update',
                            'href' => '/core/templates/update/id/' . $this->escape($row['id']),
                            'resource' => 'Core_Model_Templates',
                            'permission' => 'update',
                            'ng-click' => 'fetchHtml($event)'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/core/templates/delete/id/' . $this->escape($row['id']),
                            'resource' => 'Core_Model_Templates',
                            'permission' => 'delete',
                            'prepend' => '&nbsp;',
                            'ng-click' => 'fetchHtml($event)'));
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="row">
        <div class="span3">
            <div class="daiquiri-widget">
            <?php
            echo $this->internalLink(array(
                'text' => 'Create new mail template',
                'href' => '/core/templates/create',
                'resource' => 'Core_Model_Templates',
                'permission' => 'create',
                'prepend' => '<p>',
                'append' => '</p>',
                'ng-click' => 'fetchHtml($event)'));
            ?>
            </div>
            <div class="daiquiri-widget">
            <?php
            echo $this->internalLink(array(
                'text' => 'Export to init.php syntax',
                'href' => '/core/templates/export',
                'resource' => 'Core_Model_Templates',
                'permission' => 'export',
                'prepend' => '<p>',
                'append' => '</p>'));
            ?>
            </div>
        </div>

        <div class="span3 pull-right">
            <div class="daiquiri-widget">
            <?php echo $this->adminLink(); ?>
            </div>
        </div>
    </div>

    <div daiquiri-modal></div>
</div>
