<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php if ($this->status === 'ok'): ?>
<script type="text/javascript">
<?php if ($this->status === 'ok'): ?>
        $(document).ready(function() {
            // create the table inside the div
            $('#table').daiquiri_table({
                'rowsurl': "<?php echo $this->baseUrl('/data/viewer/rows') ?>",
                'colsurl': "<?php echo $this->baseUrl('/data/viewer/cols') ?>",
                'params': {
                    'db': "<?php echo $this->db ?>",
                    'table': "<?php echo $this->table ?>"
                },
                'success': function () {
                    if ($('.daiquiri-table-downloadable','#table').length != 0) {
                        $('#content').append('<div><button id="daiquiri-file-download-button" class="linkbutton">Download files from selected cells</button></div>')

                        $('#daiquiri-file-download-button').on('click', function () {
                            var items = [];
                            $('a','.daiquiri-table-downloadable.daiquiri-table-row-selected,.daiquiri-table-downloadable.daiquiri-table-col-selected','#table').each(function () {
                                items.push(this.href);
                            })
                            console.log(items);
                            // $('<iframe />', {
                            //     'style': 'visibility: hidden; height: 0; width: 0;',
                            //     'src': url
                            // }).appendTo(div);
                        })
                    }
                },
                'multiselect': true
            });
        });
<?php endif; ?>
</script>
<div id="table"></div>
<?php else: ?>
<p class="text-error">No Database or Table was given.</p>
<?php endif; ?>
