<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<script type="text/javascript">
    $(document).ready(function() {
        new daiquiri.data.Data('<?php echo $this->baseUrl(); ?>');
    });
</script>

<div class="main">
    <h2>Database management</h2>

    <div id="data">

        <p>Please click on a database, a table, a column or a function to show or edit its metadata.</p>
        <div class="row">
            <div class="span9">
                <div id="database-browser"></div>
            </div>
            <div class="span3">
                <div id="function-browser"></div>
            </div>
        </div>

        <div id="display">
            <div class="row">
                <div class="span3">
                    <div class="box">
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Create new database entry',
                            'href' => '/data/databases/create',
                            'class' => 'daiquiri-modal-open',
                            'prepend' => '<p>',
                            'append' => '</p>'));
                        echo $this->internalLink(array(
                            'text' => 'Create new table entry',
                            'href' => '/data/tables/create',
                            'class' => 'daiquiri-modal-open',
                            'prepend' => '<p>',
                            'append' => '</p>'));
                        echo $this->internalLink(array(
                            'text' => 'Create new column entry',
                            'href' => '/data/columns/create',
                            'class' => 'daiquiri-modal-open',
                            'prepend' => '<p>',
                            'append' => '</p>'));
                        echo $this->internalLink(array(
                            'text' => 'Create new function entry',
                            'href' => '/data/functions/create',
                            'class' => 'daiquiri-modal-open',
                            'prepend' => '<p>',
                            'append' => '</p>'));
                        echo $this->internalLink(array(
                            'text' => 'Export to init.php syntax',
                            'href' => '/data/index/export',
                            'prepend' => '<p>',
                            'append' => '</p>'));
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

