<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<script type="text/javascript">
    $(document).ready(function() {
        $('#browser').daiquiri_browser({
            'url': "<?php echo $this->baseUrl('/data/databases'); ?>",
            'action': function(opt) {
                console.log(opt);
            }
        });
    });
</script>

<h2>Database management</h2>

<div id="database-management">

    <p>Please click on a database, table or column to show or edit its metadata.</p>

    <div id="browser" style="height: 200px;"></div>

    <div class="row">
        <div class="span9"></div>
        <div class="span3"></div>
    </div>

    <div class="">
        <?php
        echo $this->internalLink(array(
            'text' => 'Export in php syntax for init.php',
            'href' => '/data/index/export',
            'prepend' => '<p>',
            'append' => '</p>'));
        ?>
    </div>
</div>
