<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<script type="text/javascript">
    $(document).ready(function() {
        // create the table inside the div
        $('#daiquiri-messages-table').daiquiri_table({
            'rowsurl': "<?php echo $this->baseUrl('/contact/messages/rows') ?>",
            'colsurl': "<?php echo $this->baseUrl('/contact/messages/cols') ?>",
        });
    });
</script>

<div class="main">
    <h2>Contact messages management</h2>

    <p id="daiquiri-messages-table"></p>

    <?php echo $this->adminLink(); ?>
</div>
