<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php if ($this->status === 'ok'): ?>
    <p>The response has been send to the user.</p>
    <?php
    echo $this->internalLink(array(
        'href' => '/admin',
        'text' => 'Back to Administration',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
<?php else: ?>
    <h2>
        Contact message by 
        <?php echo $this->escape($this->message['firstname']) . ' ' . $this->escape($this->message['lastname']); ?>
    </h2>

    <h4>Sender information</h4>
    <dl class="dl-horizontal">
        <?php foreach (array('firstname', 'lastname', 'email') as $key): ?>
            <dt><?php echo ucfirst($this->escape($key)); ?>:</dt>
            <dd><?php echo $this->escape($this->message[$key]); ?></dd>
        <?php endforeach; ?>
    </dl>

    <h4>Message</h4>
    <dl class="dl-horizontal">
        <?php foreach (array('status', 'category', 'subject', 'message') as $key): ?>
            <dt><?php echo ucfirst($this->escape($key)); ?>:</dt>
            <dd><?php echo $this->escape($this->message[$key]); ?></dd>
        <?php endforeach; ?>
    </dl>

    <h4>Your response</h4>

    <p class="text-warning">
        Your message will not be stored on the server. It will, however, 
        be send to your address as well.
    </p>

    <?php echo $this->form; ?>
<?php endif; ?>