<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <p>The response has been send to the user.</p>
        <?php echo $this->adminLink(); ?>
    <?php else: ?>
        <h2>
            Contact message by
            <?php echo $this->escape($this->message['firstname']) . ' ' . $this->escape($this->message['lastname']); ?>
        </h2>

        <h4>Sender information</h4>
        <dl class="dl-horizontal">
            <?php foreach (array('firstname', 'lastname', 'email') as $key): ?>
                <dt><?php echo ucfirst($this->escape($key)); ?></dt>
                <dd><?php echo $this->escape($this->message[$key]); ?></dd>
            <?php endforeach; ?>
        </dl>

        <h4>Message</h4>
        <dl class="dl-horizontal">
            <?php foreach (array('status', 'category', 'subject', 'message') as $key): ?>
                <dt><?php echo ucfirst($this->escape($key)); ?></dt>
                <dd><?php echo $this->escape($this->message[$key]); ?></dd>
            <?php endforeach; ?>
        </dl>

        <h4>Your response</h4>

        <p class="text-warning">
            Your message will not be stored on the server. It will, however, 
            be send to your address as well.
        </p>

        <?php echo $this->form; ?>
    <?php endif; ?>
</div>
