<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<?php
$labelOptions = array('escape' => false, 'class' => 'span1', 'style' => 'text-align: right;');
$errorOptions = array('class' => 'text-error unstyled');
?>

<fieldset id="<?php echo $this->escape($this->group->getId()) ?>" 
          class="daiquiri-form-view-script-group"
          style="margin-bottom: 0;">
    <div class="row">
        <?php
        // get the the range_xcent element
        $e = $this->group->getElement('cone_racent');
        echo $this->formLabel($e->getName(), $e->getLabel(), $labelOptions);
        ?>
        <div class="span2 inline">
            <?php echo $this->{$e->helper}($e->getName(), $e->getValue(), $e->getAttribs()); ?>
            <div class="daiquiri-form-view-script-error"><?php echo $this->formErrors($e->getMessages(), $errorOptions); ?></div>
        </div>
        <?php
        // get the the range_ycent element
        $e = $this->group->getElement('cone_decent');
        echo $this->formLabel($e->getName(), $e->getLabel(), $labelOptions);
        ?>
        <div class="span2 inline">
            <?php echo $this->{$e->helper}($e->getName(), $e->getValue(), $e->getAttribs()); ?>
            <div class="daiquiri-form-view-script-error"><?php echo $this->formErrors($e->getMessages(), $errorOptions); ?></div>
        </div>
    </div>

    <div class="row">
        <?php
        // get the the range_ymin element
        $e = $this->group->getElement('cone_rad');
        echo $this->formLabel($e->getName(), $e->getLabel(), $labelOptions);
        ?>
        <div class="span2 inline">
            <?php echo $this->{$e->helper}($e->getName(), $e->getValue(), $e->getAttribs()); ?>
            <div class="daiquiri-form-view-script-error"><?php echo $this->formErrors($e->getMessages(), $errorOptions); ?></div>

        </div>

    </div>

</fieldset>
