<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php
$labelOptions = array('escape' => false, 'class' => 'span1', 'style' => 'text-align: right;');
$errorOptions = array('class' => 'text-error unstyled');
?>

<fieldset id="<?php echo $this->escape($this->group->getId()) ?>" 
          class="daiquiri-form-view-script-group"
          style="margin-bottom: 0;">
    <div class="row">
        <?php
        // get the the range_xcent element
        $e = $this->group->getElement('cone_racent');
        echo $this->formLabel($e->getName(), $e->getLabel(), $labelOptions);
        ?>
        <div class="span2 inline">
            <?php echo $this->{$e->helper}($e->getName(), $e->getValue(), $e->getAttribs()); ?>
            <div class="daiquiri-form-view-script-error"><?php echo $this->formErrors($e->getMessages(), $errorOptions); ?></div>
        </div>
        <?php
        // get the the range_ycent element
        $e = $this->group->getElement('cone_decent');
        echo $this->formLabel($e->getName(), $e->getLabel(), $labelOptions);
        ?>
        <div class="span2 inline">
            <?php echo $this->{$e->helper}($e->getName(), $e->getValue(), $e->getAttribs()); ?>
            <div class="daiquiri-form-view-script-error"><?php echo $this->formErrors($e->getMessages(), $errorOptions); ?></div>
        </div>
    </div>

    <div class="row">
        <?php
        // get the the range_ymin element
        $e = $this->group->getElement('cone_rad');
        echo $this->formLabel($e->getName(), $e->getLabel(), $labelOptions);
        ?>
        <div class="span2 inline">
            <?php echo $this->{$e->helper}($e->getName(), $e->getValue(), $e->getAttribs()); ?>
            <div class="daiquiri-form-view-script-error"><?php echo $this->formErrors($e->getMessages(), $errorOptions); ?></div>

        </div>

    </div>

</fieldset>
