<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php

$items = array(
    'meetings' => array(
        'text' => 'Meetings',
        'href' => '/meetings/meetings',
        'resource' => 'Meetings_Model_Meetings',
        'permission' => 'index'),
    'participants' => array(
        'text' => 'Participants',
        'href' => '/meetings/participants',
        'resource' => 'Meetings_Model_Participants',
        'permission' => 'index'),    
    'participantDetailKeys' => array(
        'text' => 'Participant detail keys',
        'href' => '/meetings/participant-detail-keys',
        'resource' => 'Meetings_Model_ParticipantDetailKeys',
        'permission' => 'index'),
    'contributionTypes' => array(
        'text' => 'Contribution types',
        'href' => '/meetings/contribution-types',
        'resource' => 'Meetings_Model_ContributionTypes',
        'permission' => 'index'),
);
?>

<h2>Meetings management</h2>

<ul class="nav nav-tabs nav-stacked">
    <?php foreach ($items as $key => $value): ?>
        <li class="nav-item">
            <?php echo $this->internalLink($value); ?>
        </li>
    <?php endforeach; ?>
</ul>
