<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>
<?php if ($this->status === 'ok'): ?>
    <p>Column entry created.</p>
    <?php
    echo $this->internalLink(array(
        'text' => 'Back to data management',
        'href' => '/data/',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
<?php elseif ($this->status === 'error'): ?>
    <p>An error occurred when creating the column entry:</p>
    <p><?php
    echo $this->errors;
    ?></p>
<?php else: ?>
    <h2>Create column entry</h2>
    <?php echo $this->form; ?>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#ucd_list').after('<button name="add_ucd" id="add_ucd" type="button" class="btn">Add UCD</button>');
            $('#add_ucd').click(function() {
                if( !$.trim($('#ucd').val()) ) {
                    $('#ucd').val($('#ucd_list').val());
                } else {
                    $('#ucd').val($.trim($('#ucd').val()) + "; " + $('#ucd_list').val());
                }
            });
        });
    </script>
<?php endif; ?>