<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <p>Column entry created.</p>
        <?php
        echo $this->internalLink(array(
            'text' => 'Back',
            'href' => $this->redirect,
            'prepend' => '<p>',
            'append' => '</p>'));
        ?>
    <?php else: ?>
        <h2>Create column entry</h2>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#ucd_list').after('<button name="add_ucd" id="add_ucd" type="button" class="btn">Add UCD</button>');
                $('#add_ucd').click(function() {
                    if( !$.trim($('#ucd').val()) ) {
                        $('#ucd').val($('#ucd_list').val());
                    } else {
                        $('#ucd').val($.trim($('#ucd').val()) + "; " + $('#ucd_list').val());
                    }
                });
            });
        </script>
        <?php echo $this->form; ?>
    <?php endif; ?>
</div>
