<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Configuration</h2>

    <p class="text-warning">
        Warning! 
        Changing these parameters can make the application unusable. 
        Proceed only if you are sure what you are doing!
    </p>
    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Key</th>
                <th>Value</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <td><?php echo $this->escape($row['key']); ?></td>
                    <td><?php echo $this->escape($row['value']); ?></td>
                    <td>
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Update',
                            'href' => '/core/config/update/id/' . $this->escape($row['id']),
                            'resource' => 'Core_Model_Config',
                            'permission' => 'update'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/core/config/delete/id/' . $this->escape($row['id']),
                            'resource' => 'Core_Model_Config',
                            'permission' => 'delete',
                            'prepend' => '&nbsp;'));
                        ?>
                    </td>
                </tr>
            <?php endforeach;
            ?>
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => 'Create new configuration entry',
        'href' => '/core/config/create',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Export to init.php syntax',
        'href' => '/core/config/export',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->adminLink();
    ?>
</div>
