<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <div class="row">
            <div class="span9">
                <div class="box">
                    <p>
                        <span class="meta">FUNCTION</span>
                        <strong><?php echo $this->escape($this->data['name']); ?></strong>
                    </p>
                </div>
                <table class='table table-bordered'>
                    <?php foreach($this->data as $key => $value): ?>
                        <tr>
                            <td class="onehundredtwenty"><?php echo $this->escape($key); ?></td>
                            <td>
                                <?php echo $this->escape($value); ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </table>
            </div>
            <div class="span3">
                <div class="box">
                    <?php
                    $redirect = '/data/functions/show?id=' . $this->escape($this->data['id']);
                    echo $this->internalLink(array(
                        'text' => 'Update this function entry',
                        'href' => '/data/functions/update?id=' . $this->escape($this->data['id']) . '&redirect=' . $redirect,
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Delete this function entry',
                        'href' => '/data/functions/delete?id=' . $this->escape($this->data['id']) . '&redirect=' . $redirect,
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    ?>
                </div>
                <div class="box">
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'Create new database entry',
                        'href' => '/data/databases/create?redirect=' . $redirect,
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new table entry',
                        'href' => '/data/tables/create&redirect=' . $redirect,
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new column entry',
                        'href' => '/data/columns/create?redirect=' . $redirect,
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new function entry',
                        'href' => '/data/functions/create?redirect=' . $redirect,
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    ?>
                </div>
            </div>
        </div>
    <?php else: ?>
    <h5>Error retrieving table information</h5>
    <?php endif; ?>
</div>
