<?php

/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <h2>Manage participant status</h2>

    <table class="table table-bordered table-condensed">
        <thead>
            <tr>
                <th>Id</th>
                <th>Key</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <?php foreach ($row as $element): ?>
                    <td><?php echo $this->escape($element); ?></td>
                    <?php endforeach; ?>
                    <td>
                        <?php 
                        echo $this->internalLink(array(
                            'text' => 'Show',
                            'href' => '/meetings/participant-status/show/id/' . $this->escape($row['id']),
                            'resource' =>'Meetings_Model_ParticipantStatus',
                            'permission' => 'show',
                            'ng-click' => 'fetchHtml($event)'));
                        echo $this->internalLink(array(
                            'text' => 'Update',
                            'href' => '/meetings/participant-status/update/id/' . $this->escape($row['id']),
                            'resource' => 'Meetings_Model_ParticipantStatus',
                            'permission' => 'update',
                            'prepend' => '&nbsp;',
                            'ng-click' => 'fetchHtml($event)'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/meetings/participant-status/delete/id/' . $this->escape($row['id']),
                            'resource' => 'Meetings_Model_ParticipantStatus',
                            'permission' => 'delete',
                            'prepend' => '&nbsp;',
                            'ng-click' => 'fetchHtml($event)')); 
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="row">
        <div class="span3">
            <div class="daiquiri-widget">
            <?php
            echo $this->internalLink(array(
                'text' => 'Create participant status',
                'href' => '/meetings/participant-status/create',
                'resource' => 'Meetings_Model_ParticipantStatus',
                'permission' => 'create',
                'prepend' => '<p>',
                'append' => '</p>',
                'ng-click' => 'fetchHtml($event)'));
            ?>
            </div>
        </div>

        <div class="span3 pull-right">
            <div class="daiquiri-widget">
                <?php
                echo $this->internalLink(array(
                    'text' => 'Back to meetings management',
                    'href' => '/meetings/',
                    'prepend' => '<p>',
                    'append' => '</p>'));
                ?>
            </div>
        </div>
    </div>

    <div daiquiri-modal></div>
</div>
