<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <p>Password changed.</p>
        <?php if ($this->disable): ?>
            <p>
                For security, you account needs to be re-enabled by an administrator. 
                This can take one or two days. If you do not receive a corresponding 
                mail by then, please contact the administrators directly.
            </p>
        <?php endif; ?>
    <?php else: ?>
        <?php if (empty($this->form)): ?>
            <p>The provided url is not valid.</p>
        <?php else: ?>
            <h2>Change password</h2>
            <p>Please give your username and a new password.</p>
            <p>If you cannot remember your username, please contact the support directly.</p>
            <?php echo $this->form; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>
