<?php

/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <?php if ($this->status != 'ok'): ?>
        <h2>Contributions</h2>
        <p>The list of contributions for this meeting is not available right now.</p>
    <?php else: ?>
        <?php foreach ($this->data as $contributionType => $contributions): ?>
            <?php if (!empty($contributions)): ?>
                <h2><?php echo $contributionType; ?></h2>

                <?php foreach ($contributions as $contribution): ?>
                    <h4><?php echo $contribution['title']; ?></h4>
                    <h6><?php echo $contribution['participant_firstname'] . ' ' . $contribution['participant_lastname']; ?></h6>
                    <p><?php echo $contribution['abstract']; ?></p>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
