<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <p>User detail  updated.</p>
        <?php
        echo $this->internalLink(array(
            'text' => 'Back to user',
            'href' => '/auth/user/',
            'prepend' => '<p>',
            'append' => '</p>'));
        ?>
    <?php else: ?>
        <h2>Update user detail</h2>
        <?php if (empty($this->form)): ?>
            <p class="text-error"><?php echo $this->escape($this->error); ?></p>
        <?php else: ?>
            <?php echo $this->form; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>
