<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <h2>Template configuration</h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th style="width: 30%">Template</th>
                <th style="width: 65%">Subject</th>
                <th style="width: 5%">Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <td style="width: 30%"><?php echo $this->escape($row['template']); ?></td>
                    <td style="width: 65%"><?php echo $this->escape($row['subject']); ?></td>
                    <td style="width: 5%">
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Update',
                            'href' => '/config/templates/update/id/' . $this->escape($row['id']),
                            'resource' => 'Config_Model_Templates',
                            'permission' => 'update'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/config/templates/delete/id/' . $this->escape($row['id']),
                            'resource' => 'Config_Model_Templates',
                            'permission' => 'delete',
                            'prepend' => '&nbsp;'));
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
        echo $this->internalLink(array(
        'text' => 'Create new mail template',
        'href' => '/config/templates/create',
        'resource' => 'Config_Model_Templates',
        'permission' => 'create',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Export to init.php syntax',
        'href' => '/config/templates/export',
        'resource' => 'Config_Model_Templates',
        'permission' => 'export',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Back to Administration',
        'href' => '/admin/',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
