<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<?php if ($this->mode == 'latex'): ?>
\documentclass{artcl}
\begin{document}
<?php foreach ($this->rows as $contributionType => $rows): ?>
<?php echo '\section*{' . ucfirst($contributionType) . "} \n\n"; ?>
<?php foreach ($rows as $row): ?>
<?php echo '\subsection*{' . $row['title'] . "} \n\n"; ?>
<?php echo '\subsubsection*{' . $row['participant_firstname'] . ' ' . $row['participant_lastname'] . "}\n\n"; ?>
<?php echo $this->escape(wordwrap($row['abstract'], 100)) . "\n\n"; ?>
<?php endforeach; ?>
<?php endforeach; ?>
\end{document}
<?php else: ?>
<?php foreach ($this->rows as $contributionType => $rows): ?>
<?php echo ucfirst($contributionType) . "\n"; ?>
<?php echo str_repeat('=',strlen($contributionType)) . "\n\n"; ?>
<?php foreach ($rows as $row): ?>
<?php echo $row['title'] . ' (' . $row['participant_firstname'] . ' ' . $row['participant_lastname'] . ")\n";?>
<?php echo str_repeat('-',strlen($row['title']) + strlen($row['participant_firstname']) + strlen($row['participant_lastname']) + 4) . "\n\n"; ?>
<?php echo $this->escape(wordwrap($row['abstract'], 100)) . "\n\n"; ?>
<?php endforeach; ?>
<?php endforeach; ?>
<?php endif; ?>
