<?php

/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<link href="/daiquiri/css/table.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/daiquiri/css/modal.css" media="screen" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="/daiquiri/js/table.js"></script>
<script type="text/javascript" src="/daiquiri/js/modal.js"></script>
<script type="text/javascript" src="/daiquiri/js/admin.js"></script>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <?php
    if (isset($this->meeting)){
        echo "<h2>Contributions for: {$this->escape($this->meeting['title'])}</h2>";
        $cols = "/meetings/contributions/cols?meetingId={$this->meeting['id']}";
        $rows = "/meetings/contributions/rows?meetingId={$this->meeting['id']}";
    } else {
        echo "<h2>Contributions for all meetings</h2>";
        $cols = "/meetings/contributions/cols";
        $rows = "/meetings/contributions/rows";
    }
    ?>

    <div daiquiri-table data-cols="<?php echo $cols; ?>" data-rows="<?php echo $rows; ?>"></div>
    <div daiquiri-modal></div>

    <?php
    if (isset($this->meeting)) {
        echo $this->internalLink(array(
            'text' => 'Create new contribution for this meeting',
            'href' => '/meetings/' . $this->slug . '/contributions/create/' ,
            'prepend' => '<p>',
            'append' => '</p>'));
    }
    echo $this->internalLink(array(
        'text' => 'Back',
        'href' => $this->redirect,
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
