<?php

/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <?php if ($this->meeting !== null): ?>
    <h2><?php echo $this->escape($this->meeting['title']); ?></h2>
    <h4>Contributions</h4>
    <?php else: ?>
    <h2>Contributions</h4>
    <?php endif; ?>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Type</th>
                <th>Accepted</th>
                <?php if ($this->meeting === null): ?>
                    <th>Meeting</th>
                <?php endif; ?>
                <th>Participant</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <td><?php echo $this->escape($row['id']); ?></td>
                    <td><?php echo $this->escape($row['title']); ?></td>
                    <td><?php echo $this->escape($row['contribution_type']); ?></td>
                    <td><?php echo $row['accepted'] ? 'yes' : 'no' ?></td>
                    <?php if ($this->meeting === null): ?>
                        <td><?php echo $this->escape($row['meeting_title']); ?></td>
                    <?php endif; ?>
                    <td><?php echo $this->escape($row['participant_email']); ?></td>
                    <td>
                        <?php
                        if ($this->meeting === null) {
                            $redirect = '';
                        } else {
                            $redirect = '?redirect=/meetings/contributions/index/meetingId/' . $this->meeting['id'];
                        }

                        echo $this->internalLink(array(
                            'text' => 'Show',
                            'href' => '/meetings/contributions/show/id/' . $this->escape($row['id']) . $redirect,
                            'resource' => $this->model,
                            'permission' => 'show'));
                        echo $this->internalLink(array(
                            'text' => 'Update',
                            'href' => '/meetings/contributions/update/id/' . $this->escape($row['id']) . $redirect,
                            'resource' => $this->model,
                            'permission' => 'update',
                            'prepend' => '&nbsp;'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/meetings/contributions/delete/id/' . $this->escape($row['id']) . $redirect,
                            'resource' => $this->model,
                            'permission' => 'delete',
                            'prepend' => '&nbsp;'));
                        echo $this->internalLink(array(
                            'text' => 'Accept',
                            'href' => '/meetings/contributions/accept/id/' . $this->escape($row['id']) . $redirect,
                            'resource' => $this->model,
                            'permission' => 'accept',
                            'prepend' => '&nbsp;'));
                        echo $this->internalLink(array(
                            'text' => 'Reject',
                            'href' => '/meetings/contributions/reject/id/' . $this->escape($row['id']) . $redirect,
                            'resource' => $this->model,
                            'permission' => 'reject',
                            'prepend' => '&nbsp;'));
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => 'Back to meetings management',
        'href' => '/meetings',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
