<?php

/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <h2>Registration</h4>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Email</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <td><?php echo $this->escape($row['email']); ?></td>
                    <td>
                        <?php 
                        $link = '/auth/registration/validate/id/' . $row['id'] . '/code/' . $row['code'];
                        echo $this->internalLink(array(
                            'text' => 'Validate',
                            'href' => $link,
                            'append' => '&nbsp;'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/auth/registration/delete/id/' . $row['id'],
                            'resource' => 'Meetings_Model_Registration',
                            'permission' => 'delete'));
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => 'Back to user management',
        'href' => '/auth/user',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
