<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<script type="text/javascript">
    $(document).ready(function() {
        // create the table inside the div
        $('#daiquiri-jobs-table').daiquiri_table({
            'rowsurl': "<?php echo $this->baseUrl('/query/jobs/rows') ?>",
            'colsurl': "<?php echo $this->baseUrl('/query/jobs/cols') ?>",
            'success': function() {
                $('#daiquiri-jobs-table tbody a').click(function(){
                    new daiquiri.Modal({
                        'url': this.href,
                        'width': 700,
                        'success': function() {
                            daiquiri.table.items['daiquiri-jobs-table'].rows();
                        }
                    });
                    return false;
                });
            }
        });
    });
</script>

<div class="main">
    <h2>Query jobs management</h2>

    <p id="daiquiri-jobs-table"></p>

    <?php echo $this->adminLink(); ?>
</div>
