<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Sorry, but there has been an error.</h2>
    <h3><?php echo $this->message ?></h3>

    <?php if (isset($this->exception)): ?>
        <h4>Exception information:</h4>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>

        <h4>Stack trace:</h4>
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>

        <h4>Request Parameters:</h4>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
    <?php else: ?>
        <p>We are sorry for any inconvenience.</p>
    <?php endif ?>
</div>
