<?php

/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <h2><?php echo $this->escape($this->title); ?></h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Id</th>
                <th>Contribution Type</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $row): ?>
                <tr>
                    <?php foreach ($row as $element): ?>
                    <td><?php echo $this->escape($element); ?></td>
                    <?php endforeach; ?>
                    <td>
                        <?php 
                        echo $this->internalLink(array(
                            'text' => 'Show',
                            'href' => $this->options['show']['url'] . '?id=' . $this->escape($row['id']),
                            'resource' => $this->model,
                            'permission' => 'show'));
                        echo $this->internalLink(array(
                            'text' => 'Update',
                            'href' => $this->options['update']['url'] . '?id=' . $this->escape($row['id']),
                            'resource' => $this->model,
                            'permission' => 'update',
                            'prepend' => '&nbsp;'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => $this->options['delete']['url'] . '?id=' . $this->escape($row['id']),
                            'resource' => $this->model,
                            'permission' => 'delete',
                            'prepend' => '&nbsp;')); 
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => $this->options['create']['title'],
        'href' => $this->options['create']['url'],
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Back to meetings management',
        'href' => '/meetings',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
