<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <h2>Status Messages</h2>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th>Key</th>
                <th>Message</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <td><?php echo $this->escape($row['key']); ?></td>
                    <td><?php echo $this->escape($row['value']); ?></td>
                    <td>
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'Update',
                            'href' => '/config/messages/update/id/' . $this->escape($row['id']),
                            'resource' => 'Config_Model_Messages',
                            'permission' => 'update'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/config/messages/delete/id/' . $this->escape($row['id']),
                            'resource' => 'Config_Model_Messages',
                            'permission' => 'delete',
                            'prepend' => '&nbsp;'));
                        ?>
                    </td>
                </tr>
            <?php endforeach;
            ?>
        </tbody>
    </table>

    <?php
    echo $this->internalLink(array(
        'text' => 'Create new status message',
        'href' => '/config/messages/create',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Export to init.php syntax',
        'href' => '/config/messages/export',
        'resource' => 'Config_Model_Messages',
        'permission' => 'export',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Back to Administration',
        'href' => '/admin/',
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>
