<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <div class="row">
            <div class="span9">
                <div class="box">
                    <p>
                        <span class="meta">TABLE</span>
                        <strong><?php echo $this->escape($this->row['database']); ?>.<?php echo $this->escape($this->row['name']); ?></strong>
                    </p>
                </div>
                <table class='table table-bordered'>
                    <?php foreach($this->row as $key => $value): ?>
                        <?php if ($key !== 'columns'): ?>
                        <tr>
                            <td class="onehundredtwenty"><?php echo $this->escape($key); ?></td>
                            <td>
                                <?php echo $this->escape($value); ?>
                            </td>
                        </tr>
                        <?php endif; ?>
                    <?php endforeach ?>
                    <?php if (!empty($this->row['columns'])): ?>
                    <tr>
                        <td class="onehundredtwenty">Columns</td>
                        <td>
                            <ul class="unstyled">
                                <?php foreach($this->row['columns'] as $column): ?>
                                <li><?php echo $this->escape($column['name']); ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </td>
                    </tr>
                    <?php endif; ?>
                </table>
            </div>
            <div class="span3">
                <div class="box">
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'Update this table entry',
                        'href' => '/data/tables/update?id=' . $this->escape($this->row['id']),
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Delete this table entry',
                        'href' => '/data/tables/delete?id=' . $this->escape($this->row['id']),
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    ?>
                </div>
                <div class="box">
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'Create new database entry',
                        'href' => '/data/databases/create',
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new table entry',
                        'href' => '/data/tables/create?databaseId=' . $this->escape($this->row['database_id']),
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new column entry',
                        'href' => '/data/columns/create?tableId=' . $this->escape($this->row['id']),
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    echo $this->internalLink(array(
                        'text' => 'Create new function entry',
                        'href' => '/data/functions/create',
                        'class' => 'daiquiri-modal-open',
                        'prepend' => '<p>',
                        'append' => '</p>'));
                    ?>
                </div>
            </div>
        </div>
    <?php else: ?>
    <h5>Error retrieving table information</h5>
    <?php endif; ?>
</div>
