<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<?php if ($this->status === 'ok'): ?>
    <p>Query successfully submitted.</p>
<?php elseif ($this->status === 'plan'): ?>
    <p>Query submitted.</p>
    <p>You need to view and approve the <a href="<?php echo $this->escape($this->redirect); ?>">query plan</a>.
<?php else: ?>
    <script type="text/javascript">      
        $(document).ready(function() {
            $('#sql_query').daiquiri_codemirror();

            $('#daiquiri-form-query-sql').daiquiri_query_buttons();

            $('.daiquiri-query-example').click(function() {
                var string = $(this).attr('data-toggle');

                // clear textarea
                $('#sql_query').val('');
                $('#sql_query').daiquiri_codemirror_clear();

                // insert query
                $('#sql_query').insertAtCaret(string);
                $('#sql_query').daiquiri_codemirror_insertAtCaret(string);
            });

            $('#sql_clear').click(function(){
                $('#sql_query').val('');
                $('#sql_query').daiquiri_codemirror_clear();
            });
        });
    </script>

    <h4><?php echo $this->escape($this->formOptions['title']); ?></h4>

    <p><?php echo $this->escape($this->formOptions['help']); ?></p>
    <?php echo $this->form; ?>
    <?php if ($this->status === 'error' && array_key_exists("form", $this->errors)): ?>
        <p class="text-error">An error has occured.</p>
        <ul class="text-error">
            <?php foreach ($this->errors['form'] as $error): ?>
                <?php if (is_array($error)): ?>
                    <?php foreach ($error as $e): ?>
                        <li><?php echo $this->escape($e); ?></li>
                    <?php endforeach; ?>
                <?php else: ?>
                    <li><?php echo $this->escape($error); ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <div class="accordion" id="sql-query-accordion">
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#sql-query-accordion-2" href="#sql-query-accordion-2">
                    Example Queries
                </a>
            </div>
            <div id="sql-query-accordion-2" class="accordion-body collapse">
                <div class="accordion-inner">
                    <?php echo $this->action('examples', 'account', 'query'); ?>
                </div>
            </div>
        </div>

        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#sql-query-accordion-1" href="#sql-query-accordion-1">
                    Database browser
                </a>
            </div>
            <div id="sql-query-accordion-1" class="accordion-body collapse">
                <div class="accordion-inner">
                    <div id="browser"></div>
                    <p class="help-block">A double click will paste the database/table/column identifier into the query field.</p>
                </div>
            </div>
        </div>
    </div> 
<?php endif; ?>
