<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php if ($this->status === 'ok'): ?>
    <p>Query successfully submitted.</p>
<?php elseif ($this->status === 'plan'): ?>
    <p>Query submitted.</p>
    <p>You need to view and approve the <a href="<?php echo $this->escape($this->redirect); ?>">query plan</a>.
<?php elseif ($this->status === 'form'): ?>
    <script type="text/javascript">      
        $(document).ready(function() {
            $('#sql_query').daiquiri_codemirror();

            $('#daiquiry-form-query-sql').daiquiri_query_buttons();
                                
            $('.daiquiri-query-example').click(function() {
                var string = $(this).attr('data-toggle');
                $('#sql_query').insertAtCaret(string);
                $('#sql_query').daiquiri_codemirror_insertAtCaret(string);
            });

            $('#sql_clear').click(function(){
                $('#sql_query').val('');
                $('#sql_query').daiquiri_codemirror_clear();
            });
        });
    </script>

    <h4><?php echo $this->escape($this->formOptions['title']); ?></h4>

    <p><?php echo $this->escape($this->formOptions['help']); ?></p>
    <?php echo $this->form; ?>
    <?php if (!empty($this->errors['form'])): ?>
        <p class="text-error">An error has occured.</p>
        <ul class="text-error">
            <?php foreach ($this->errors['form'] as $error): ?>
                <?php if (is_array($error)): ?>
                    <?php foreach ($error as $e): ?>
                        <li><?php echo $this->escape($e); ?></li>
                    <?php endforeach; ?>
                <?php else: ?>
                    <li><?php echo $this->escape($error); ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <div class="accordion" id="sql-query-accordion">
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#sql-query-accordion-2" href="#sql-query-accordion-2">
                    Example Queries
                </a>
            </div>
            <div id="sql-query-accordion-2" class="accordion-body collapse">
                <div class="accordion-inner">
                    <?php echo $this->action('example-queries', 'index', 'query'); ?>
                </div>
            </div>
        </div>

        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#sql-query-accordion-1" href="#sql-query-accordion-1">
                    Database browser
                </a>
            </div>
            <div id="sql-query-accordion-1" class="accordion-body collapse">
                <div class="accordion-inner">
                    <div id="browser"></div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
