<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<?php if ($this->status === 'ok'): ?>
    <p>Query successfully submitted.</p>
<?php elseif ($this->status === 'redirect'): ?>
    <?php $this->redirector($this->redirect); ?>
<?php elseif ($this->status === 'form'): ?>
    <script type="text/javascript">
        var _daiquiri_cm;
                            
        $(document).ready(function() {
            _daiquiri_cm = CodeMirror.fromTextArea($('#sql_query').get(0), {
                mode: 'text/x-mysql',
                indentWithTabs: false,
                smartIndent: true,
                matchBrackets : true,
                lineNumbers: true,
                lineWrapping: true,
                autofocus: true
            });
                                            
            // adjust with of input field, since span9 does not work with CodeMirror
            _daiquiri_cm.setSize($('#sql_query').css('width'),null);

            $("#<?php echo $this->escape($this->form->getAttrib('id')); ?>").daiquiri_query_buttons();
                                
            $(".daiquiri-query-example").click(function() {
                $('#sql_query').insertAtCaret($(this).attr('data-toggle'));

                if(typeof _daiquiri_cm !== undefined) {
                    var pos = _daiquiri_cm.getCursor();
                    pos['ch'] += $(this).attr('data-toggle').length;
                    _daiquiri_cm.replaceSelection($(this).attr('data-toggle'));
                    _daiquiri_cm.setCursor(pos);
                    _daiquiri_cm.focus();
                }
            });

            $('#sql_clear').click(function(){
                $('#sql_query').val('');

                if(typeof _daiquiri_cm !== "undefined") {
                    _daiquiri_cm.setValue('');
                }
            });
        });
    </script>

    <h4><?php echo $this->escape($this->formOptions['title']); ?></h4>

    <p><?php echo $this->escape($this->formOptions['help']); ?></p>
    <?php echo $this->form; ?>
    <?php if (!empty($this->errors['form'])): ?>
        <p class="text-error">An error has occured.</p>
        <ul class="text-error">
            <?php foreach ($this->errors['form'] as $error): ?>
                <?php if (is_array($error)): ?>
                    <?php foreach ($error as $e): ?>
                        <li><?php echo $this->escape($e); ?></li>
                    <?php endforeach; ?>
                <?php else: ?>
                    <li><?php echo $this->escape($error); ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <div class="accordion" id="sql-query-accordion">
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#sql-query-accordion-2" href="#sql-query-accordion-2">
                    Example Queries
                </a>
            </div>
            <div id="sql-query-accordion-2" class="accordion-body collapse">
                <div class="accordion-inner">
                    <?php echo $this->action('example-queries', 'index', 'query'); ?>
                </div>
            </div>
        </div>

        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#sql-query-accordion-1" href="#sql-query-accordion-1">
                    Database browser
                </a>
            </div>
            <div id="sql-query-accordion-1" class="accordion-body collapse">
                <div class="accordion-inner">
                    <div id="browser"></div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
