<?php

/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <h2>Manage non-validated meeting registrations</h4>

    <table class="table table-bordered table-condensed">
        <thead>
            <tr>
                <th>Email</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <td><?php echo $this->escape($row['email']); ?></td>
                    <td>
                        <?php 
                        $link = '/meetings/registration/validate/id/' . $row['id'] . '/code/' . $row['code'];
                        echo $this->internalLink(array(
                            'text' => 'Show',
                            'href' => '/meetings/registration/show/id/' . $row['id'],
                            'resource' => 'Meetings_Model_Registration',
                            'permission' => 'show',
                            'append' => '&nbsp;',
                            'ng-click' => 'fetchHtml($event)'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/meetings/registration/delete/id/' . $row['id'],
                            'resource' => 'Meetings_Model_Registration',
                            'permission' => 'delete',
                            'append' => '&nbsp;',
                            'ng-click' => 'fetchHtml($event)'));
                        echo $this->internalLink(array(
                            'text' => 'Validate',
                            'href' => $link));
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="row">
        <div class="span3 pull-right">
            <div class="daiquiri-widget">
                <?php
                echo $this->internalLink(array(
                    'text' => 'Back to meetings management',
                    'href' => '/meetings/',
                    'prepend' => '<p>',
                    'append' => '</p>'));
                ?>
            </div>
        </div>
    </div>

    <div daiquiri-modal></div>
</div>
