<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <p>Your registration was successful and a mail was send to the provided address.</p>
    <?php elseif ($this->status === 'validate'): ?>
        <p>Your registration was successful and a validation mail was send to the provided address.</p>
        <p>Please follow the instructions in the mail to validate your registration.</p>
    <?php else: ?>
        <?php echo $this->message; ?>
        <?php if (!empty($this->form)): ?>
            <?php echo $this->form; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#fieldset-contributions input[type="checkbox"]').each(function () {
            if (!this.checked) {
                var type = $(this).attr('id').match(/(\w+)_bool/)[1];
                $('#' + type + '_title').parents('.control-group').hide();
                $('#' + type + '_abstract').parents('.control-group').hide();
            }
        })

        $('#fieldset-contributions input[type="checkbox"]').change(function(){
            var type = $(this).attr('id').match(/(\w+)_bool/)[1];
            if (this.checked) {
                $('#' + type + '_title').parents('.control-group').show();
                $('#' + type + '_abstract').parents('.control-group').show();
            } else {
                $('#' + type + '_title').parents('.control-group').hide();
                $('#' + type + '_abstract').parents('.control-group').hide();
            }
        });
    })
</script>
