<?php

/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <h2>Registration</h2>
    
    <?php if ($this->status === 'ok'): ?>
        <p>Your registration was successful and a mail was send to the provided address.</p>
    <?php elseif ($this->status === 'validate'): ?>
        <p>Your registration was successful and a validation mail was send to the provided address.</p>
        <p>Please follow the instructions in the mail to validate your registration.</p>
    <?php else: ?>
        <?php if (empty($this->form)): ?>
            <p>The registration for this meeting is currently closed.</p>
        <?php else: ?>
            <p>
                In order to register for the meeting, we kindly ask you to fill out the following form.
            </p>
            <?php echo $this->form; ?>
        <?php endif; ?>
    <?php endif; ?>

</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#arrival').datepicker({
            format: 'yyyy-mm-dd'
        });
        $('#departure').datepicker({
            format: 'yyyy-mm-dd'
        });

        $('.daiquiri-toggle-control-group').each(function () {
            if (!this.checked) {
                var type = $(this).attr('id').match(/(\w+)_bool/)[1];
                $('#' + type + '_title').parents('.control-group').hide();
                $('#' + type + '_abstract').parents('.control-group').hide();
            }
        })

        $('.daiquiri-toggle-control-group').change(function(){
            var type = $(this).attr('id').match(/(\w+)_bool/)[1];
            if (this.checked) {
                $('#' + type + '_title').parents('.control-group').show();
                $('#' + type + '_abstract').parents('.control-group').show();
            } else {
                $('#' + type + '_title').parents('.control-group').hide();
                $('#' + type + '_abstract').parents('.control-group').hide();
            }
        });
    })
</script>
