<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <p>Thank you for using our Contact Form. You should get a response within the next days.</p>
        <?php
        echo $this->internalLink(array(
            'href' => '/',
            'text' => 'Back to Home',
            'prepend' => '<p>',
            'append' => '</p>'));
        ?>
    <?php else: ?>
        <h2>Contact Form</h2>
        <p>
            Please send us your questions/comments/bug reports etc. via the following form.
        </p>
        <?php echo $this->form; ?>
    <?php endif; ?>
</div>
