<?php

/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <h2>Meetings management</h2>

    <div class="row">
        <div class="span9">
        <?php foreach ($this->rows as $row): ?>
        <div class="daiquiri-widget">
            <div class="pull-right">
            <?php
                echo $this->internalLink(array(
                    'text' => 'Show',
                    'href' => '/meetings/meetings/show/id/' . $this->escape($row['id']),
                    'resource' => 'Meetings_Model_Meetings',
                    'permission' => 'show',
                    'append' => '&nbsp;',
                    'ng-click' => 'fetchHtml($event)'));
                echo $this->internalLink(array(
                    'text' => 'Update',
                    'href' => '/meetings/meetings/update/id/' . $this->escape($row['id']),
                    'resource' => 'Meetings_Model_Meetings',
                    'permission' => 'update',
                    'append' => '&nbsp;',
                    'ng-click' => 'fetchHtml($event)'));
                echo $this->internalLink(array(
                    'text' => 'Delete',
                    'href' => '/meetings/meetings/delete/id/' . $this->escape($row['id']),
                    'resource' => 'Meetings_Model_Meetings',
                    'permission' => 'delete',
                    'ng-click' => 'fetchHtml($event)'));
                ?>
            </div>

            <p><strong><?php echo $this->escape($row['title']); ?></strong></p>
            <p>from <?php echo $this->escape($row['begin']); ?> to <?php echo $this->escape($row['end']); ?></p>
            <p><?php echo $this->escape($row['description']); ?></p>

            <ul class="unstyled pull-right">
                <li>
                    Export participants:
                <?php
                echo $this->internalLink(array(
                    'text' => 'names',
                    'href' => '/meetings/' . $this->escape($row['slug']) . '/participants/export',
                    'resource' => 'Meetings_Model_Participants',
                    'permission' => 'export',
                    'append' => ', '));
                echo $this->internalLink(array(
                    'text' => 'names and email',
                    'href' => '/meetings/' . $this->escape($row['slug']) . '/participants/export/mode/mail',
                    'resource' => 'Meetings_Model_Participants',
                    'permission' => 'export',
                    'append' => ', '));
                echo $this->internalLink(array(
                    'text' => 'names and affiliation',
                    'href' => '/meetings/' . $this->escape($row['slug']) . '/participants/export/mode/affiliation',
                    'resource' => 'Meetings_Model_Participants',
                    'permission' => 'export'));
                ?>
                </li>
                <li>
                    Export contributions:
                <?php
                echo $this->internalLink(array(
                    'text' => 'plain text',
                    'href' => '/meetings/' . $this->escape($row['slug']) . '/contributions/export',
                    'resource' => 'Meetings_Model_Contributions',
                    'permission' => 'index',
                    'append' => ', '));
                echo $this->internalLink(array(
                    'text' => 'latex sourcecode',
                    'href' => '/meetings/' . $this->escape($row['slug']) . '/contributions/export/mode/latex',
                    'resource' => 'Meetings_Model_Contributions',
                    'permission' => 'index'));
                ?>
                </li>
            </ul>

            <ul class="unstyled">
                <?php
                echo $this->internalLink(array(
                    'text' => 'Show registration page',
                    'href' => '/meetings/' . $this->escape($row['slug']) . '/registration/',
                    'resource' => 'Meetings_Model_Registration',
                    'permission' => 'register',
                    'prepend' => '<li>',
                    'append' => '</li>'));
                echo $this->internalLink(array(
                    'text' => 'Show participants',
                    'href' => '/meetings/' . $this->escape($row['slug']) . '/participants/',
                    'resource' => 'Meetings_Model_Participants',
                    'permission' => 'index',
                    'prepend' => '<li>',
                    'append' => '</li>'));
                echo $this->internalLink(array(
                    'text' => 'Show contributions',
                    'href' => '/meetings/' . $this->escape($row['slug']) . '/contributions/',
                    'resource' => 'Meetings_Model_Contributions',
                    'permission' => 'index',
                    'prepend' => '<li>',
                    'append' => '</li>'));
                ?>
            </ul>
        </div>
    <?php endforeach; ?>
        </div>
        <div class="span3">
            <div class="daiquiri-widget">
                <?php
                echo $this->internalLink(array(
                    'text' => 'Create new meeting',
                    'href' => '/meetings/meetings/create',
                    'resource' => 'Meetings_Model_Meetings',
                    'permission' => 'create',
                    'prepend' => '<p>',
                    'append' => '</p>',
                    'ng-click' => 'fetchHtml($event)'));
                ?>
            </div>
            <div class="daiquiri-widget">
                <?php
                echo $this->internalLink(array(
                    'text' => 'Show all registrations',
                    'href' => '/meetings/registration',
                    'resource' => 'Meetings_Model_Registration',
                    'permission' => 'index', 
                    'prepend' => '<p>',
                    'append' => '</p>'));
                ?>
            </div>
            <div class="daiquiri-widget">
                <?php
                echo $this->internalLink(array(
                    'text' => 'Manage participant detail keys',
                    'href' => '/meetings/participant-detail-keys',
                    'resource' => 'Meetings_Model_ParticipantDetailKeys',
                    'permission' => 'index',
                    'prepend' => '<p>',
                    'append' => '</p>'));
                echo $this->internalLink(array(
                    'text' => 'Manage participant status',
                    'href' => '/meetings/participant-status',
                    'resource' => 'Meetings_Model_ParticipantStatus',
                    'permission' => 'index',
                    'prepend' => '<p>',
                    'append' => '</p>'));
                echo $this->internalLink(array(
                    'text' => 'Manage contribution types',
                    'href' => '/meetings/contribution-types',
                    'resource' => 'Meetings_Model_ContributionTypes',
                    'permission' => 'index',
                    'prepend' => '<p>',
                    'append' => '</p>'));
                ?>
            </div>
            <div class="daiquiri-widget">
                <?php echo $this->adminLink(); ?>
            </div>
        </div>
    </div>

    <div daiquiri-modal></div>
</div>
