<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2><?php echo $this->escape($this->row['title']); ?></h2>
    <table class="table table-bordered">
        <tbody>
            <?php foreach ($this->row as $key => $value): ?>
                <?php if (substr($key, -strlen('_id')) !== '_id'): ?>
                <tr>
                    <td class="onehundredeighty"><?php echo ucfirst(str_replace('_',' ',$this->escape($key))); ?></td>
                    <td>
                        <?php 
                        if (is_array($value)) {
                            echo $this->escape(implode(',',$value)); 
                        } else {
                            echo $this->escape($value);
                        }
                        ?>
                    </td>
                </tr>
                <?php endif; ?>
            <?php endforeach; ?>  
        </tbody>
    </table>

    <div class="row">
        <div class="span6">
            <?php
            echo $this->internalLink(array(
                'text' => 'Update meeting details',
                'href' => '/meetings/meetings/update/id/' . $this->escape($this->row['id']) . '?redirect=/meetings/meetings/show/id/' . $this->escape($this->row['id']),
                'resource' => 'Meetings_Model_Meetings',
                'permission' => 'update',
                'prepend' => '<p>',
                'append' => '</p>'));
            echo $this->internalLink(array(
                'text' => 'Show participants table for this meeting',
                'href' => '/meetings/' . $this->escape($this->row['slug']) . '/participants/?redirect=/meetings/meetings/show/id/' . $this->escape($this->row['id']),
                'resource' => 'Meetings_Model_Participants',
                'permission' => 'index',
                'prepend' => '<p>',
                'append' => '</p>'));
            echo $this->internalLink(array(
                'text' => 'Show contributions table for this meeting',
                'href' => '/meetings/' . $this->escape($this->row['slug']) . '/contributions/?redirect=/meetings/meetings/show/id/' . $this->escape($this->row['id']),
                'resource' => 'Meetings_Model_Contributions',
                'permission' => 'index',
                'prepend' => '<p>',
                'append' => '</p>'));
            echo $this->internalLink(array(
                'text' => 'Back',
                'href' => $this->redirect,
                'prepend' => '<p>',
                'append' => '</p>'));
            ?>
        </div>
        <div class="span6">
            <?php
            echo $this->internalLink(array(
                'text' => 'Show registration page for this meeting',
                'href' => '/meetings/' . $this->escape($this->row['slug']) . '/registration/register/?redirect=/meetings/meetings/show/id/' . $this->escape($this->row['id']),
                'resource' => 'Meetings_Model_Registration',
                'permission' => 'register',
                'prepend' => '<p>',
                'append' => '</p>'));
            echo $this->internalLink(array(
                'text' => 'Show public participants page for this meeting',
                'href' => '/meetings/' . $this->escape($this->row['slug']) . '/info/participants/',
                'resource' => 'Meetings_Model_Participants',
                'permission' => 'index',
                'prepend' => '<p>',
                'append' => '</p>'));
            echo $this->internalLink(array(
                'text' => 'Show public contributions page for for this meeting',
                'href' => '/meetings/' . $this->escape($this->row['slug']) . '/info/contributions/',
                'resource' => 'Meetings_Model_Contributions',
                'permission' => 'index',
                'prepend' => '<p>',
                'append' => '</p>'));
            ?>
        </div>

    </div>
</div>
