<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
        <h2>You don't have the permission to view this page.</h2>
        <p>
            You might want to login or logout and login as a different user.
        </p>
        <p>
            <?php echo $this->loginLink(); ?>
        </p>
    <?php else: ?>
        <h2>You need to be logged in to view this page.</h2>
        <?php
        $redirect = preg_replace('`' . preg_quote($this->baseUrl()) . '`', '', $this->url());
        echo $this->action('index', 'login', 'auth', array('redirect' => $redirect));
        ?>
    <?php endif; ?>
</div>
