<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <?php if ($this->hasIdentity): ?>
        <h2>You don't have the permission to view this page.</h2>
        <p>
            You might want to login or logout and login as a different user. <br />
            <?php echo $this->loginLink(); ?>
        </p>
    <?php else: ?>
        <h2>You need to be logged in to view this page.</h2>
        <?php
        $redirect = preg_replace('`' . preg_quote($this->baseUrl()) . '`', '', $this->url());
        echo $this->action('index', 'login', 'auth', array('redirect' => $redirect));
        ?>
    <?php endif; ?>
</div>
