<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <p>Query successfully submitted.</p>
    <?php elseif ($this->status === 'redirect'): ?>
        <?php $this->redirector($this->redirect); ?>
    <?php elseif ($this->status === 'form'): ?>
        <h4><?php echo $this->escape($this->formOptions['title']); ?></h4>
        <p><?php echo $this->escape($this->formOptions['help']); ?></p>
        <?php echo $this->form; ?>
        <?php if (!empty($this->errors['form'])): ?>
            <p class="text-error">An error has occured.</p>
            <ul class="text-error">
                <?php foreach ($this->errors['form'] as $error): ?>
                    <?php if (is_array($error)): ?>
                        <?php foreach ($error as $e): ?>
                            <li><?php echo $this->escape($e); ?></li>
                        <?php endforeach ?>
                    <?php else: ?>
                        <li><?php echo $this->escape($error); ?></li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
    <?php endif ?>
</div>
