<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <h2>Static file alias management</h2>

    <table class="table table-condensed table-bordered">
        <thead>
            <tr>
                <th>Alias</th>
                <th>Path</th>
                <th>Published for</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->rows as $row): ?>
                <tr>
                    <td><?php echo $this->escape($row['alias']); ?></td>
                    <td><?php echo $this->escape($row['path']); ?></td>
                    <td><?php echo $this->escape($row['publication_role']); ?></td>
                    <td>
                        <?php
                        echo $this->internalLink(array(
                            'text' => 'View',
                            'href' => '/data/' . $this->escape($row['alias']) . '/',
                            'resource' => 'Data_Model_Static',
                            'permission' => 'file'));
                        echo $this->internalLink(array(
                            'text' => 'Update',
                            'href' => '/data/static/update/id/' . $this->escape($row['id']),
                            'resource' => 'Data_Model_Static',
                            'permission' => 'update',
                            'prepend' => '&nbsp;',
                            'ng-click' => 'fetchHtml($event)'));
                        echo $this->internalLink(array(
                            'text' => 'Delete',
                            'href' => '/data/static/delete/id/' . $this->escape($row['id']),
                            'resource' => 'Data_Model_Static',
                            'permission' => 'delete',
                            'prepend' => '&nbsp;',
                            'ng-click' => 'fetchHtml($event)'));
                        ?>
                    </td>
                </tr>
            <?php endforeach;
            ?>
        </tbody>
    </table>

    <div class="row">
        <div class="span3">
            <?php
            echo $this->internalLink(array(
                'text' => 'Create static file alias',
                'href' => '/data/static/create',
                'resource' => 'Data_Model_Static',
                'permission' => 'create',
                'prepend' => '<div class="daiquiri-widget"><p>',
                'append' => '</p></div>',
                'ng-click' => 'fetchHtml($event)'));
            echo $this->internalLink(array(
                'text' => 'Export to init.php syntax',
                'href' => '/data/static/export',
                'prepend' => '<div class="daiquiri-widget"><p>',
                'append' => '</p></div>'));
            ?>
        </div>

        <div class="span3 pull-right">
            <div class="daiquiri-widget">
            <?php echo $this->adminLink(); ?>
            </div>
        </div>
    </div>

    <div daiquiri-modal></div>
</div>
