<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <?php if ($this->status === 'pending'): ?>
        <p>Your file is beeing created... Please wait...</p>
    <?php elseif ($this->status === 'ok'): ?>
        <p>You can now download the file using:</p>
        <p>
            <a target="_blank" href="<?php echo $this->escape($this->link); ?>">
                <?php echo $this->escape($this->link); ?>
            </a>
        </p>
    <?php else: ?>
        <?php if(isset($this->form)): ?> 
            <h4>Download table</h4>
            <p>
                Please select the format for your download:
            </p>
            <p>
                <?php echo $this->form; ?>
            </p>
        <?php else: ?>
            <p class="text-error"><?php echo $this->error; ?></p>
        <?php endif; ?>
    <?php endif; ?>
</div>
