<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <?php if ($this->status === 'pending'): ?>
        <p>Your file is beeing created... Please wait...</p>
    <?php elseif ($this->status === 'ok'): ?>
        <p>You can now download the file using:</p>
        <p>
            <a target="_blank" href="<?php echo $this->escape($this->link); ?>">
                <?php echo $this->escape($this->link); ?>
            </a>
        </p>
    <?php else: ?>
        <?php if(isset($this->form)): ?> 
            <h4>Download table</h4>
            <p>
                Please select the format for your download:
            </p>
            <p>
                <?php echo $this->form; ?>
            </p>
        <?php else: ?>
            <p class="text-error"><?php echo $this->error; ?></p>
        <?php endif; ?>
    <?php endif; ?>
</div>
