<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<script type="text/javascript">
    $(document).ready(function() {
        daiquiri.common.startPoll(3000);
        var query = new daiquiri.query.Query('<?php echo Daiquiri_Config::getInstance()->getSiteUrl() ?>');
    });
</script>

<div class="main">
    <h2>Query interface</h2>

    <div class="row">
        <div class="span3">
            <?php if (!empty($this->message)): ?>
            <div id="message" class="daiquiri-widget">
                <ul class="nav nav-pills nav-stacked">
                    <li class="nav-header">Database Status</li>
                    <li class="nav-item"><p><?php echo $this->escape($this->message); ?></p></li>
                </ul>
            </div>
            <?php endif; ?>
            <div id="jobs" class="daiquiri-widget">
                <!-- ajax widget for job display -->
            </div>
        </div>
        <div class="span9">
            <div id="query" class=""> 
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <?php foreach ($this->forms as $key => $form): ?>
                            <li id="<?php echo $this->escape($key); ?>-form-tab-header" 
                                class="<?php if (!empty($form['default'])) echo 'active default-tab'; ?>" >
                                <a href="#<?php echo $key ?>-form-tab" data-toggle="tab"><?php echo $this->escape($form['title']); ?></a>
                            </li>
                        <?php endforeach; ?>
                        <li id="details-tab-header">
                            <a href="#details-tab" data-toggle="tab">Job Details</a>
                        </li>
                        <li id="results-tab-header">
                            <a href="#results-tab" data-toggle="tab">Results Table</a>
                        </li>
                        <li id="plot-tab-header">
                            <a href="#plot-tab" data-toggle="tab">Plot</a>
                        </li>
                        <li id="download-tab-header">
                            <a href="#download-tab" data-toggle="tab">Download</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <?php foreach ($this->forms as $key => $form): ?>
                            <div class="tab-pane <?php if (isset($form['default']) && $form['default'] == true) echo 'active'; ?>" id="<?php echo $this->escape($key); ?>-form-tab">
                                <?php echo $this->action('index', 'form', 'query', array('form' => $key)); ?>
                            </div>
                        <?php endforeach; ?>
                        <div class="tab-pane" id="details-tab"></div>
                        <div class="tab-pane" id="results-tab">
                            <div id="results-table"></div>
                        </div>
                        <div class="tab-pane row" id="plot-tab">
                            <div class="span6">
                                <div id="plot-container">
                                    <div id="plot"></div>
                                </div>
                            </div>
                            <div id="plot-form" class="span3"></div>
                        </div>
                        <div class="tab-pane" id="download-tab"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
