<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<script type="text/javascript">
    $(document).ready(function() {
        daiquiri.common.startPoll(3000);
        var query = new daiquiri.query.Query('<?php echo Daiquiri_Config::getInstance()->getSiteUrl() ?>');
    });
</script>

<div class="main">
    <h2>Query interface</h2>

    <div class="row">
        <div class="span3">
            <?php if (!empty($this->message)): ?>
            <div id="message" class="daiquiri-widget">
                <ul class="nav nav-pills nav-stacked">
                    <li class="nav-header">Database Status</li>
                    <li class="nav-item"><p><?php echo $this->escape($this->message); ?></p></li>
                </ul>
            </div>
            <?php endif; ?>
            <div id="jobs" class="daiquiri-widget">
                <!-- ajax widget for job display -->
            </div>
        </div>
        <div class="span9">
            <div id="query" class=""> 
                <div class="tabbable">
                    <ul class="nav nav-tabs">
                        <?php foreach ($this->forms as $key => $form): ?>
                            <li id="<?php echo $this->escape($key); ?>-form-tab-header" 
                                class="<?php if (!empty($form['default'])) echo 'active default-tab'; ?>" >
                                <a href="#<?php echo $key ?>-form-tab" data-toggle="tab"><?php echo $this->escape($form['title']); ?></a>
                            </li>
                        <?php endforeach; ?>
                        <li id="details-tab-header">
                            <a href="#details-tab" data-toggle="tab">Job Details</a>
                        </li>
                        <li id="results-tab-header">
                            <a href="#results-tab" data-toggle="tab">Results Table</a>
                        </li>
                        <li id="plot-tab-header">
                            <a href="#plot-tab" data-toggle="tab">Plot</a>
                        </li>
                        <li id="download-tab-header">
                            <a href="#download-tab" data-toggle="tab">Download</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <?php foreach ($this->forms as $key => $form): ?>
                            <div class="tab-pane <?php if (isset($form['default']) && $form['default'] == true) echo 'active'; ?>" id="<?php echo $this->escape($key); ?>-form-tab">
                                <?php echo $this->action('index', 'form', 'query', array('form' => $key)); ?>
                            </div>
                        <?php endforeach; ?>
                        <div class="tab-pane" id="details-tab"></div>
                        <div class="tab-pane" id="results-tab">
                            <div id="results-table"></div>
                        </div>
                        <div class="tab-pane row" id="plot-tab">
                            <div class="span6">
                                <div id="plot-container">
                                    <div id="plot"></div>
                                </div>
                            </div>
                            <div id="plot-form" class="span3"></div>
                        </div>
                        <div class="tab-pane" id="download-tab"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
