<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<link href="<?php echo $this->baseUrl('/daiquiri/css/query.css'); ?>" media="screen" rel="stylesheet" type="text/css" >
<script type="text/javascript" src="<?php echo $this->baseUrl('/daiquiri/js/query.js'); ?>"></script>

<div class="main" ng-app="query" ng-controller="QueryController"
    ng-init='options = <?php echo Zend_Json::encode($this->options); ?>'>

    <h2>Query interface</h2>

    <div class="row">

        <!-- sidebar  -->

        <div class="span3">

            <!-- database status -->

            <div id="database-status" class="daiquiri-widget nav nav-pills nav-stacked">
                <div class="nav-header">Database status</div>
                <div class="nav-item">
                    <p ng-show="account.database.message">
                        {{account.database.message}}
                    </p>
                    <p ng-show="account.database.nactive === 0">
                        There is no job in the queue.
                    </p>
                    <p ng-show="account.database.nactive === 1">
                        There is one job in the queue.
                    </p>
                    <p ng-show="account.database.nactive > 1">
                        There are {{account.database.nactive}} jobs in the queue.
                    </p>
                    <p ng-show="account.database.guest == true">
                        You are using the guest user. For a personal account, please sign up <a href="/auth/registration/register">here</a>.
                    </p>
                    <p ng-show="account.database.guest === true">
                        The guest user is using {{account.database.quota.used}} of its quota of {{account.database.quota.max}}.
                    </p>
                    <p ng-show="account.database.guest === false">
                        You are using {{account.database.quota.used}} of your quota of {{account.database.quota.max}}.
                    </p>
                    <p ng-show="account.database.quota.exceeded" class="text-error">
                        Please remove some jobs to free space or contact the administrators.
                    </p>
                </div>
            </div>

            <!-- new query menu -->

            <ul id="database-status" class="daiquiri-widget nav nav-pills nav-stacked">
                <li class="nav-header">New Query</li>
                <?php foreach ($this->options['forms'] as $form): ?>
                    <li class="nav-item"
                        ng-class="{active: account.active.form == '<?php echo $this->escape($form['key']); ?>'}"
                        ng-click="activateForm('<?php echo $this->escape($form['key']); ?>')">
                        <a href="" ><?php echo $this->escape($form['title']); ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>

            <!-- jobs -->

            <ul id="jobs" class="daiquiri-widget nav nav-pills nav-stacked">
                <li class="nav-header">Job list</li>
                <li class="nav-item {{job.id == account.active.job ? 'active' : ''}}"
                    ng-repeat="job in account.jobs  | orderBy:'-timestamp'">
                    <a href="" ng-click="activateJob(job.id)" >
                        <i class="icon-ok pull-right" rel="tooltip" data-placement="right" data-original-title="Job is done" ng-show="job.status == 'success'"></i>
                        <i class="icon-warning-sign pull-right" rel="tooltip" data-placement="right" data-original-title="Job terminated with an error"  ng-show="job.status == 'error'"></i>
                        <i class="icon-play pull-right" rel="tooltip" data-placement="right" data-original-title="Job is running" ng-show="job.status == 'running'"></i>
                        <i class="icon-remove pull-right" rel="tooltip" data-placement="right" data-original-title="Job was killed" ng-show="job.status == 'killed'"></i>
                        <i class="icon-trash pull-right" rel="tooltip" data-placement="right" data-original-title="Job was deleted" ng-show="job.status == 'deleted'"></i>
                        <i class="icon-pause pull-right" rel="tooltip" data-placement="right" data-original-title="Job is queued" ng-show="job.status == 'queued'"></i>
                        <i class="icon-ban-circle pull-right" rel="tooltip" data-placement="right" data-original-title="Job timed out" ng-show="job.status == 'timeout'"></i>
                        <div class="daiquiri-query-jobs-item">{{job.table}}</div>
                    </a>
                </li>
            </ul>

        </div>

        <!-- main content  -->

        <div class="span9">
            <div id="query" class="">
                <div class="tabbable">

                    <!-- tab header -->

                    <ul class="nav nav-tabs">
                        <li id="submit-tab-header" ng-show="account.active.form" ng-class="{active: account.active.form}">
                            <a href="#submit-tab" data-toggle="tab" ng-click="tabclick($event)">New Query</a>
                        </li>
                        <li id="overview-tab-header" ng-show="account.active.job">
                            <a href="#overview-tab" data-toggle="tab" ng-click="tabclick($event)">Job Overview</a>
                        </li>
                        <li id="results-tab-header" ng-show="account.active.job && account.job.status == 'success'">
                            <a href="#results-tab" data-toggle="tab" ng-click="tabclick($event)">Results Table</a>
                        </li>
                        <?php if ($this->samp): ?>
                        <li id="samp-tab-header" ng-show="account.active.job && account.job.status == 'success'">
                            <a href="#samp-tab" data-toggle="tab" ng-click="tabclick($event)">SAMP</a>
                        </li>
                        <?php endif; ?>
                        <li id="plot-tab-header" ng-show="account.active.job && account.job.status == 'success'">
                            <a href="#plot-tab" data-toggle="tab" ng-click="tabclick($event)">Plot</a>
                        </li>
                        <li id="download-tab-header" ng-show="account.active.job && account.job.status == 'success'">
                            <a href="#download-tab" data-toggle="tab" ng-click="tabclick($event)">Download</a>
                        </li>
                    </ul>

                    <!-- tabs -->

                    <div class="tab-content">

                        <!-- submit tab -->

                        <div class="tab-pane" id="submit-tab" ng-show="account.active.form" ng-controller="SubmitController">
                            <?php foreach ($this->options['forms'] as $form): ?>
                            <div ng-show="account.active.form == '<?php echo $form['key']; ?>'">
                                <?php echo $this->action('index', 'form', 'query', array('form' => $form['key'])); ?>
                            </div>
                            <?php endforeach; ?>

                            <?php if (!empty($this->plan['enabled'])): ?>
                            <div daiquiri-modal transclude ng-show="dialog.enabled == 'plan'">
                                <h2>Query plan</h2>
                                <form id="plan" name="plan" class="daiquiri-form">
                                    <fieldset class="daiquiri-form-group">
                                        <div class="control-group">
                                            <div class="controls">
                                                <?php if (empty($this->plan['editable'])): ?>
                                                <textarea id="plan_query" class="daiquiri-query-plan" readonly>{{dialog.values.plan}}</textarea>
                                                <?php else: ?>
                                                <textarea id="plan_query" class="daiquiri-query-plan codemirror"></textarea>
                                                <?php endif; ?>
                                                <ul class="unstyled text-error" ng-show="errors.plan_query">
                                                    <li ng-repeat="error in errors.plan_query">{{error}}</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </fieldset>
                                    <?php if (!empty($this->plan['mail'])): ?>
                                    <fieldset class="daiquiri-form-inline-group inline">
                                        <button type="button" class="linkbutton daiquiri-query-plan-mail-button">
                                            Send this plan as a bug report to the Daiquiri developers (opens a new window/tab).
                                        </button>
                                    </fieldset>
                                    <?php endif; ?>
                                    <fieldset id="fieldset-actiongroup" class="form-action">
                                        <input type="submit" name="submit" value="Submit this plan" class="btn btn-primary" ng-click="submitPlan()" />
                                        <input type="submit" name="cancel" value="Cancel" class="btn" ng-click="hideDialog()" />
                                    </fieldset>
                                </form>
                            </div>
                            <?php endif; ?>
                        </div>

                        <!-- job overview tab -->

                        <div class="tab-pane" id="overview-tab" ng-show="account.active.job">
                            <h4>Overview for job `{{account.job.table}}`</h4>
                            <p>
                                On this page, you can find an overview about a submitted query job. For a table view of the results, the plotting tool, and to access the download form, please use the tabs at the top of the page.
                            </p>
                            <div class="daiquiri-widget nav">
                                <div class="nav-header">Query</div>
                                <div class="nav-item">
                                    <pre id="overview-query" class="cm-s-default"></pre>
                                </div>
                                <div class="nav-item">
                                    <button class="linkbutton" ng-click="pasteQuery('overview-query')">
                                        Open new query form with this query
                                    </button>
                                </div>
                            </div>

                            <div class="daiquiri-widget nav">
                                <div class="nav-header">Job parameters</div>
                                <div class="nav-item">
                                    <dl class="dl-horizontal">
                                        <dt>Job status</dt>
                                        <dd ng-class="{
                                            'text-success': account.job.status == 'success',
                                            'text-warning': account.job.status == 'timeout',
                                            'text-error': account.job.status == 'error',
                                            'text-info': account.job.status == 'queued'}">
                                            {{account.job.status}}
                                        </dd>

                                        <div ng-show="account.job.status == 'error'">
                                            <dt>Error</dt>
                                            <dd class="text-error">
                                                {{account.job.error}}
                                            </dd>
                                        </div>

                                        <dt>Full database table name</dt>
                                        <dd>{{account.job.database}}.{{account.job.table}}</dd>

                                        <dt>Internal job id</dt>
                                        <dd>{{account.job.id}}</dd>

                                        <dt>Time submitted</dt>
                                        <dd>{{account.job.time}}</dd>

                                        <div ng-show="account.job.timeQueue != null">
                                            <dt>Time in queue</dt>
                                            <dd>{{account.job.timeQueue}} s</dd>
                                        </div>

                                        <div ng-show="account.job.timeQuery != null">
                                            <dt>Time for query</dt>
                                            <dd>{{account.job.timeQuery}} s</dd>
                                        </div>

                                        <div ng-show="account.job.nrows != null">
                                            <dt>Number of rows</dt>
                                            <dd>{{account.job.nrows}}</dd>
                                        </div>
                                    </dl>
                                </div>
                                <div class="nav-item">
                                    <div ng-show="account.job.status == 'success'">
                                        <button class="linkbutton" ng-click="showDialog('rename')">
                                            Rename the job's result table
                                        </button>
                                    </div>
                                    <div ng-show="account.job.status == 'running' || account.job.status == 'pending'">
                                        <button class="linkbutton" ng-click="showDialog('kill')">
                                            Kill the job
                                        </button>
                                    </div>
                                    <div ng-show="account.job.status != 'running' && account.job.status != 'pending'">
                                        <button class="linkbutton" ng-click="showDialog('remove')">
                                            Remove the job
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div class="daiquiri-widget nav">
                                <div class="nav-header">Additional infomation</div>
                                <div class="nav-item">
                                    <dl class="dl-horizontal">
                                        <div ng-repeat="element in account.job.additional">
                                            <dt>{{element.name}}</dt>
                                            <dd>{{element.value}}</dd>
                                        </div>
                                    <dl>
                                </div>
                            </div>

                            <div class="daiquiri-widget nav" ng-show="account.job.cols">
                                <div class="nav-header">Database columns</div>
                                <div class="nav-item">
                                    <table class="table table-condensed">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Type</th>
                                                <th>Unit</th>
                                                <th>UCD</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr ng-repeat="element in account.job.cols">
                                                <td>{{element.name}}</td>
                                                <td>{{element.type}}</td>
                                                <td>{{element.unit}}</td>
                                                <td>{{element.ucd}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                            <div class="daiquiri-widget nav" ng-show="account.job.plan">
                                <div class="nav-header">Query plan</div>
                                <div class="nav-item">
                                    <pre id="overview-plan" class="cm-s-default"></pre>
                                </div>
                            </div>

                            <div class="daiquiri-widget nav" ng-show="account.job.actualQuery">
                                <div class="nav-header">Actual query</div>
                                <div class="nav-item">
                                    <pre id="overview-actualQuery" class="cm-s-default"></pre>
                                </div>
                            </div>
                        </div>

                        <!-- results table tab -->

                        <div class="tab-pane" id="results-tab" ng-show="account.active.job">
                            <div ng-controller="ResultsController">
                                <div daiquiri-table></div>
                            </div>
                        </div>

                        <!-- samp tab -->

                        <?php if ($this->samp): ?>
                        <div class="tab-pane" id="samp-tab" ng-show="account.active.job" ng-controller="SampController">

                            <h4>Simple Application Messaging Protocol (SAMP)</h4>

                            <p>
                                <a href="http://www.ivoa.net/documents/SAMP/" target="_blank">SAMP</a> is an <a href="http://www.ivoa.net/" target="_blank">IVOA</a> messaging protocol that enables astronomy software tools to interoperate and communicate.
                            </p>
                            <p>
                                It lets you transfer the result table of a query to an application on you client and is supported by tools like <a href="http://www.star.bris.ac.uk/~mbt/topcat/" target="_blank">TOPCAT</a> and <a href="http://aladin.u-strasbg.fr/" target="_blank">Aladin</a>. Starting one of these programs will open a <em>SAMP Hub</em>. When registering to the Hub you usually get a security warning, which you have to approve in order to proceed.
                            </p>

                            <div class="daiquiri-widget nav">
                                <div class="nav-header">SAMP Connection</div>

                                <div class="nav-item" ng-show="connected">
                                    <table class="table table-condensed daiquiri-samp-clients">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th>Client</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr ng-repeat="client in clients">
                                                <td><img ng-show="client.icon" ng-src="{{client.icon}}"></img></td>
                                                <td>{{client.name}}</td>
                                                <td>
                                                    <a href="" ng-show="client.subs.ping" ng-click="ping(client.id)">Ping {{client.name}}</a>
                                                    <a href="" ng-show="client.subs.send" ng-click="send(client.id)">Send table to {{client.name}}</a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="nav-item">
                                    <button class="linkbutton" ng-click="register()" ng-hide="connected">Register with a local SAMP Hub</button>
                                    <button class="linkbutton" ng-click="unregister()" ng-show="connected">Disconnect from SAMP Hub</button>
                                </div>
                            </div>
                            <ul class="unstyled text-error" ng-show="errors.connection">
                                <li ng-repeat="error in errors.connection">{{error}}</li>
                            </ul>

                            <div daiquiri-modal transclude ng-show="dialog.enabled=='samp'">
                                <h2>SAMP</h2>
                                <p>{{dialog.samp}}</p>
                                <form name="samp" class="daiquiri-form">
                                    <fieldset id="fieldset-passwordgroup" class="form-action">
                                        <input type="submit" name="submit" value="Ok" class="btn btn-primary" ng-click="hideDialog()" />
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                        <?php endif; ?>

                        <!-- plot tab -->

                        <div class="tab-pane" id="plot-tab" ng-show="account.active.job" ng-controller="PlotController">
                            <div id="plot-area" class="daiquiri-widget">
                                <div id="plot-canvas"></div>
                                <div id="plot-xlabel">{{labels.x}}</div>
                                <div id="plot-ylabel">{{labels.y}}</div>
                            </div>
                            <form id="plot-form" name="plot" ng-submit="createPlot(plot.$valid)">
                                <div class="daiquiri-widget">
                                    <fieldset>
                                        <div class="control-group">
                                            <label for="plot_x" class="span1">X axis</label>
                                            <select id="plot_x" name="plot_x" class="span3"
                                                    ng-options="col.name for col in account.job.cols"
                                                    ng-model="values.plot_x">
                                                    <option value="" class="muted">Select a column</option>
                                            </select>
                                            <ul class="unstyled text-error" ng-show="errors.plot_x">
                                                <li ng-repeat="error in errors.plot_x">{{error}}</li>
                                            </ul>
                                        </div>
                                        <div class="control-group">
                                            <label for="plot_x_min" class="span1">X range</label>
                                            <input type="text" name="plot_x_min" id="plot_x_min" class="span1" ng-model="values.plot_x_min" />
                                            <input type="text" name="plot_x_max" id="plot_x_max" class="span1" ng-model="values.plot_x_max" />
                                            <select id="plot_x_scale" name="plot_x_scale" class="span2" ng-model="values.plot_x_scale">
                                                <option value="lin">Linear</option>
                                                <option value="log">Logarithmic</option>
                                            </select>
                                            <ul class="unstyled text-error" ng-show="errors.plot_x_range">
                                                <li ng-repeat="error in errors.plot_x_range">{{error}}</li>
                                            </ul>
                                        </div>
                                    </fieldset>

                                    <fieldset>
                                        <div class="control-group">
                                            <label for="plot_y" class="span1">Y axis</label>
                                            <select id="plot_y" name="plot_y" class="span3"
                                                    ng-options="col.name for col in account.job.cols"
                                                    ng-model="values.plot_y">
                                                    <option value="" class="muted">Select a column</option>
                                            </select>
                                            <ul class="unstyled text-error" ng-show="errors.plot_y">
                                                <li ng-repeat="error in errors.plot_y">{{error}}</li>
                                            </ul>
                                        </div>
                                        <div class="control-group">
                                            <label for="plot_y_min" class="span1">Y range</label>
                                            <input type="text" name="plot_y_min" id="plot_y_min" class="span1" ng-model="values.plot_y_min" />
                                            <input type="text" name="plot_y_max" id="plot_y_max" class="span1" ng-model="values.plot_y_max" />
                                            <select id="plot_y_scale" name="plot_y_scale" class="span2" ng-model="values.plot_y_scale">
                                                <option value="lin">Linear</option>
                                                <option value="log">Logarithmic</option>
                                            </select>
                                            <ul class="unstyled text-error" ng-show="errors.plot_y_range">
                                                <li ng-repeat="error in errors.plot_y_range">{{error}}</li>
                                            </ul>
                                        </div>
                                    </fieldset>
                                </div>

                                <fieldset class="pull-right">
                                    <select id="plot_nrows" name="plot_nrows" class="span3" ng-model="values.plot_nrows">
                                        <option value="100">Limit to 100 rows</option>
                                        <option value="1000">Limit to 1000 rows</option>
                                        <option value="10000">Limit to 10000 rows</option>
                                    </select>
                                </fieldset>

                                <fieldset class="form-inline">
                                    <input type="submit" name="plot_submit" id="plot_submit" value="Create plot" class="btn btn-primary">
                                    <button name="plot_reset" id="plot_reset" type="button" class="btn" ng-click="resetPlot()">Reset</button>
                                </fieldset>
                            </form>

                            <ul class="unstyled text-error" ng-show="errors.form">
                                <li ng-repeat="error in errors.form">{{error}}</li>
                            </ul>
                        </div>

                        <!-- download tab -->

                        <div class="tab-pane" id="download-tab" ng-show="account.active.job" ng-controller="DownloadController">
                            <h4>Download table `{{account.job.table}}`</h4>
                            <div>
                                <p>
                                    For further processing of the data, you can download the results table to your local machine. For this file several formats are available. Please choose a format for the download from the list below.
                                </p>
                            </div>

                            <?php echo $this->action('index', 'download', 'query'); ?>

                            <p class="text-info" ng-show="account.job.download.status == 'pending'">
                                Your file is being created... Please wait...
                            </p>

                            <div ng-show="account.job.download.status == 'ok'">
                                <p>
                                    You can now download the file using:
                                </p>
                                <p>
                                    <a class="daiquiri-query-download-link" target="_blank" href="{{account.job.download.link}}">{{account.job.download.link}}</a>
                                </p>
                                <p>
                                    To download the file in a different format, please choose from the list above and click "Download table" again.
                                </p>
                                <p>
                                    Sometimes it can be nessesary to create the download file on the server anew. Please click <button class="linkbutton" ng-click="regenerateTable()">here</button> to regenerate the file.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- rename job dialog -->

    <div daiquiri-modal transclude ng-show="dialog.enabled=='rename'">
        <h2>Rename table</h2>
        <p class="text-error" ng-show="dialog.errors">{{dialog.errors.form}}</p>
        <form name="rename">
            <fieldset id="fieldset-tablerenamegroup" class="form-horizontal">
                <div class="control-group">
                    <label for="tablename" class="control-label required">New name of the table</label>
                    <div class="controls">
                        <input type="text" name="tablename" id="tablename" ng-model="dialog.values.tablename" />
                        <ul class="unstyled text-error" ng-show="dialog.errors.tablename">
                            <li ng-repeat="error in dialog.errors.tablename">{{error}}</li>
                        </ul>
                    </div>
                </div>
            </fieldset>
            <fieldset id="fieldset-actiongroup" class="form-action">
                <input type="submit" name="submit" value="Rename table" class="btn btn-primary" ng-click="renameJob()" />
                <input type="submit" name="cancel" value="Cancel" class="btn" ng-click="hideDialog()" />
            </fieldset>
        </form>
    </div>

    <!-- kill job dialog -->

    <div daiquiri-modal transclude ng-show="dialog.enabled=='kill'">
        <h2>Kill job</h2>
        <p class="text-error" ng-show="dialog.errors.form">{{dialog.errors.form}}</p>
        <form name="kill" class="daiquiri-form-danger">
            <fieldset id="fieldset-actiongroup" class="form-action">
                <input type="submit" name="submit" value="Kill job" class="btn btn-danger" ng-click="killJob()" />
                <input type="submit" name="cancel" value="Cancel" class="btn" ng-click="hideDialog()" />
            </fieldset>
        </form>
    </div>

    <!-- remove job dialog -->

    <div daiquiri-modal transclude ng-show="dialog.enabled=='remove'">
        <h2>Remove Job</h2>
        <p class="text-error" ng-show="dialog.errors.form">{{dialog.errors.form}}</p>
        <form name="kill" class="daiquiri-form-danger">
            <fieldset id="fieldset-actiongroup" class="form-action">
                <input type="submit" name="submit" value="Remove job" class="btn btn-danger" ng-click="removeJob()" />
                <input type="submit" name="cancel" value="Cancel" class="btn" ng-click="hideDialog()" />
            </fieldset>
        </form>
    </div>

    <!-- info modal -->

    <div daiquiri-modal transclude ng-show="dialog.enabled=='submitted'">
        <h2>Query submitted</h2>
        <p>Your query has been submitted as job {{dialog.table}}.</p>
        <p>When the job is done you can obtain the results via the job browser on the left side.</p>
        <form name="info" class="daiquiri-form">
            <fieldset id="fieldset-passwordgroup" class="form-action">
                <input type="submit" name="submit" value="Ok" class="btn btn-primary" ng-click="hideDialog()" />
            </fieldset>
        </form>
    </div>
</div>
