<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  See the NOTICE file distributed with this work for additional
 *  information regarding copyright ownership. You may obtain a copy
 *  of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
?>

<div class="main">
    <?php if ($this->status === 'ok'): ?>
        <p>Query successfully submitted.</p>
    <?php elseif ($this->status === 'redirect'): ?>
        <?php $this->redirector($this->redirect); ?>
    <?php elseif ($this->status === 'form'): ?>
        <h4><?php echo $this->escape($this->formOptions['title']); ?></h4>
        <p><?php echo $this->escape($this->formOptions['help']); ?></p>
        <?php echo $this->form; ?>
        <?php if (!empty($this->errors['form'])): ?>
            <p class="text-error">An error has occured.</p>
            <ul class="text-error">
                <?php foreach ($this->errors['form'] as $error): ?>
                    <?php if (is_array($error)): ?>
                        <?php foreach ($error as $e): ?>
                            <li><?php echo $this->escape($e); ?></li>
                        <?php endforeach ?>
                    <?php else: ?>
                        <li><?php echo $this->escape($error); ?></li>
                    <?php endif ?>
                <?php endforeach ?>
            </ul>
        <?php endif ?>
    <?php endif ?>
</div>
