<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<script type="text/javascript">
    // $(document).ready(function() {
    //     // create the user table inside the div
    //     $('#user-table').daiquiri_table({
    //         "rowsurl": "<?php echo $this->baseUrl('/auth/user/rows') ?>",
    //         "colsurl": "<?php echo $this->baseUrl('/auth/user/cols') ?>",
    //         'success': function() {
    //             $('#user-table tbody a').click(function(){
    //                 new daiquiri.Modal({
    //                     'url': this.href,
    //                     'width': 700,
    //                     'success': function() {
    //                         daiquiri.table.items['user-table'].rows();
    //                     }
    //                 });
    //                 return false;
    //             });
    //         }
    //     });
    //     $('#show-registered').on('click', function() {
    //         $('#user-table-pager-search input').val('registered');
    //         $('#user-table-pager-search').submit();
    //         return false;
    //     });
    // });
</script>

<link href="/daiquiri/css/table.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/daiquiri/js/table.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl('/daiquiri/js/user.js'); ?>"></script>

<div class="main" ng-app="user" ng-controller="UserController">
    <h2>User management</h2>

    <div>{{test}}</div>

    <div daiquiri-table></div>




<!--         <p>
            <a href="#" id="show-registered">Show registered users only</a>
        </p> -->



    <?php
    /*
    echo $this->internalLink(array(
        'href' => '/auth/user/create',
        'text' => 'Create new user',
        'resource' => 'Auth_Model_User',
        'permission' => 'create',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'href' => '/auth/registration/',
        'text' => 'Manage registrations',
        'resource' => 'Auth_Model_Registration',
        'permission' => 'index',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Export to init.php syntax',
        'href' => '/auth/user/export/',
        'resource' => 'Auth_Model_User',
        'permission' => 'export',
        'prepend' => '<p>',
        'append' => '</p>'));
    echo $this->internalLink(array(
        'text' => 'Export mail addresses',
        'href' => '/auth/user/export/mode/mail',
        'resource' => 'Auth_Model_User',
        'permission' => 'export',
        'prepend' => '<p>',
        'append' => '&nbsp'));
    echo $this->internalLink(array(
        'text' => '(active)',
        'href' => '/auth/user/export/mode/mail/status/active',
        'resource' => 'Auth_Model_User',
        'permission' => 'export',
        'append' => '</p>'));
    echo $this->adminLink();
    */
    ?>
</div>
