<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<link href="/daiquiri/css/table.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/daiquiri/css/modal.css" media="screen" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="/daiquiri/js/table.js"></script>
<script type="text/javascript" src="/daiquiri/js/list.js"></script>
<script type="text/javascript" src="/daiquiri/js/modal.js"></script>
<script type="text/javascript" src="/daiquiri/js/admin.js"></script>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <h2>User management</h2>

    <div daiquiri-table data-cols="/auth/user/cols" data-rows="/auth/user/rows"></div>
    
    <div class="row">
        <div class="span3">
            <div class="daiquiri-widget">
            <?php
            echo $this->internalLink(array(
                'href' => '/auth/user/create',
                'text' => 'Create a new user',
                'resource' => 'Auth_Model_User',
                'permission' => 'create',
                'prepend' => '<p>',
                'append' => '</p>',
                'ng-click' => 'fetchHtml($event)'));
            ?>
            </div>

            <div class="daiquiri-widget">
            <?php
            echo $this->internalLink(array(
                'href' => '/auth/registration/',
                'text' => 'Manage registrations',
                'resource' => 'Auth_Model_Registration',
                'permission' => 'index',
                'prepend' => '<p>',
                'append' => '</p>'));
            echo $this->internalLink(array(
                'text' => 'Export to init.php syntax',
                'href' => '/auth/user/export/',
                'resource' => 'Auth_Model_User',
                'permission' => 'export',
                'prepend' => '<p>',
                'append' => '</p>'));
            echo $this->internalLink(array(
                'text' => 'Export mail addresses',
                'href' => '/auth/user/export/mode/mail',
                'resource' => 'Auth_Model_User',
                'permission' => 'export',
                'prepend' => '<p>'));
            echo $this->internalLink(array(
                'text' => '(active)',
                'href' => '/auth/user/export/mode/mail/status/active',
                'resource' => 'Auth_Model_User',
                'permission' => 'export',
                'prepend' => '&nbsp;',
                'append' => '</p>'));
            ?>
            </div>
        </div>

        <div class="span3 pull-right">
            <div class="daiquiri-widget">
                <?php echo $this->adminLink(); ?>
            </div>
        </div>
    </div>

    <div daiquiri-modal></div>
</div>
