<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main" ng-app="admin" ng-controller="AdminController">
    <h2>User management</h2>

    <div daiquiri-table data-cols="/auth/user/cols" data-rows="/auth/user/rows"></div>

    <div class="row">
        <div class="span3">
            <?php
            echo $this->internalLink(array(
                'href' => '/auth/user/create',
                'text' => 'Create a new user',
                'resource' => 'Auth_Model_User',
                'permission' => 'create',
                'prepend' => '<div class="daiquiri-widget"><p>',
                'append' => '</p></div>',
                'ng-click' => 'fetchHtml($event)'));
            ?>
            <div class="daiquiri-widget">
                <ul class="unstyled">
                    <li>Export emails:
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'all',
                        'href' => '/auth/user/export/mode/mail',
                        'resource' => 'Auth_Model_User',
                        'permission' => 'export',
                        'append' => ',&nbsp;'));
                    echo $this->internalLink(array(
                        'text' => 'active',
                        'href' => '/auth/user/export/mode/mail/status/active',
                        'resource' => 'Auth_Model_User',
                        'permission' => 'export'));
                    ?>
                    </li>
                </ul>
            </div>
        </div>

        <div class="span3">
            <div class="daiquiri-widget">
                <ul class="unstyled">
                    <li>
                        <a href="#" ng-click="search('registered')">Show newly registered users</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="span3 pull-right">
            <?php
            $items = $this->internalLink(array(
                'href' => '/auth/registration/',
                'text' => 'Manage registrations',
                'resource' => 'Auth_Model_Registration',
                'permission' => 'index',
                'prepend' => '<p>',
                'append' => '</p>'))
            . $this->internalLink(array(
                'href' => '/auth/detail-keys/',
                'text' => 'Manage user detail keys',
                'resource' => 'Auth_Model_DetailKeys',
                'permission' => 'index',
                'prepend' => '<p>',
                'append' => '</p>'));
            ?>
            <?php if (!empty($items)): ?>
            <div class="daiquiri-widget">
                <?php echo $items ?>
            </div>
            <?php endif; ?>

            <div class="daiquiri-widget">
                <?php echo $this->adminLink(); ?>
            </div>
        </div>
    </div>

    <div daiquiri-modal></div>
</div>
