<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<?php
$id = $this->row['id'];
unset($this->row['role_id']);
unset($this->row['status_id']);
?>

<div class="main">
    <h2>Details of user "<?php echo $this->escape($this->row['username']); ?>"</h2>

    <h4>User information</h4>

    <dl class="dl-horizontal">
        <?php foreach (array_merge(
            array('id', 'username', 'email', 'role', 'status'),
            Daiquiri_Config::getInstance()->auth->details->toArray()
        ) as $key): ?>
        <dt><?php echo $this->escape(ucfirst($key)); ?></dt>
        <dd><?php echo $this->escape($this->row[$key]); ?></dd>
        <?php unset($this->row[$key]); ?>
        <?php endforeach; ?>
    </dl>

    <h4>Additional information</h4> 

    <?php if (!empty($this->row)): ?>
    <dl class="dl-horizontal">
        <?php foreach ($this->row as $key => $value): ?>
        <dt><?php echo $this->escape(ucfirst($key)); ?></dt>
        <dd>
            <?php echo $this->escape($value); ?>
            <?php
                echo $this->internalLink(array(
                    'text' => '<i class="icon-pencil"></i>',
                    'href' => "/auth/details/update?id={$id}&key={$key}",
                    'target' => '_blank',
                    'append' => '&nbsp;'));
                echo $this->internalLink(array(
                    'text' => '<i class="icon-remove"></i>',
                    'href' => "/auth/details/delete?id={$id}&key={$key}",
                    'target' => '_blank'));
            ?>
        </dd>
        <?php endforeach; ?>
    </dl>
    <?php else: ?>
        <p>none</p>
    <?php endif; ?>
</div>