<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<?php
$id = $this->row['id'];
unset($this->row['role_id']);
unset($this->row['status_id']);
?>

<div class="main">
    <h2>Details of user "<?php echo $this->escape($this->row['username']); ?>"</h2>

    <h4>User information</h4>

    <table class="table table-condensed">
        <thead>
            <tr>
                <th class="span3">Key</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach (array('id', 'username', 'email', 'role', 'status') as $key): ?>
                <tr>
                    <td><?php echo ucfirst($this->escape($key)); ?></td>
                    <td><?php echo $this->escape($this->row[$key]); ?></td>
                </tr>
                <?php unset($this->row[$key]); ?>
            <?php endforeach; ?>
            <?php foreach (Daiquiri_Auth::getInstance()->getDetailKeys() as $key): ?>
                <?php if (isset($this->row[$key])): ?>
                <tr>
                    <td><?php echo ucfirst($this->escape($key)); ?></td>
                    <td><?php echo $this->escape($this->row[$key]); ?></td>
                </tr>
                <?php unset($this->row[$key]); ?>
                <?php endif ?>
            <?php endforeach; ?>   
        </tbody>
    </table>

    <h4>Additional information</h4> 

    <table class="table table-condensed">
        <thead>
            <tr>
                <th class="span3">Key</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->row as $key => $value): ?>
                <tr>
                    <td><?php echo ucfirst($this->escape($key)); ?></td>
                    <td><?php echo $this->escape($value); ?></td>
                    <td>
                    <?php
                    echo $this->internalLink(array(
                        'text' => '<i class="icon-pencil"></i>',
                        'href' => "/auth/details/update?id={$id}&key={$key}",
                        'target' => '_blank',
                        'append' => '&nbsp;'));
                    echo $this->internalLink(array(
                        'text' => '<i class="icon-remove"></i>',
                        'href' => "/auth/details/delete?id={$id}&key={$key}",
                        'target' => '_blank'));
                    ?>
                </tr>
            <?php endforeach; ?>  
        </tbody>
    </table>
    
    <?php
    echo $this->internalLink(array(
        'text' => 'Back',
        'class' => 'daiquiri-modal-close',
        'href' => $this->redirect,
        'prepend' => '<p>',
        'append' => '</p>'));
    ?>
</div>