<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Table management</h2>

    <?php foreach ($this->databases as $database): ?>
        <table class='table table-bordered'>
            <?php foreach ($database as $dbKey => $dbValue): ?>
                <tr>
                    <td class="onehundredtwenty"><?php echo ucfirst($this->escape($dbKey)); ?></td>
                    <td>
                        <?php if (is_array($dbValue)): ?>
                            <?php foreach ($dbValue as $table): ?>
                                <div class="accordion" id="accordion-table-<?php echo $this->escape($table['id']); ?>">
                                    <div class="accordion-group">
                                        <div class="accordion-heading">
                                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse-table-<?php echo $this->escape($table['id']); ?>">
                                                <?php echo $this->escape($table['name']); ?>
                                            </a>
                                        </div>
                                        <div id="collapse-table-<?php echo $this->escape($table['id']); ?>" class="accordion-body collapse">
                                            <div class="accordion-inner">
                                                <table class='table table-bordered'>
                                                    <?php foreach ($table as $tableKey => $tableValue): ?>
                                                        <tr>
                                                            <td class="onehundredtwenty"><?php echo ucfirst($this->escape($tableKey)); ?></td>
                                                            <td>
                                                                <?php if (is_array($tableValue)): ?>
                                                                    <?php foreach ($tableValue as $col): ?>
                                                                        <div class="accordion" id="accordion-col-<?php echo $this->escape($col['id']); ?>">
                                                                            <div class="accordion-group">
                                                                                <div class="accordion-heading">
                                                                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse-col-<?php echo $col['id'] ?>">
                                                                                        <?php echo $this->escape($col['name']); ?>
                                                                                    </a>
                                                                                </div>
                                                                                <div id="collapse-col-<?php echo $this->escape($col['id']); ?>" class="accordion-body collapse">
                                                                                    <div class="accordion-inner">
                                                                                        <table class='table table-bordered'>
                                                                                            <?php foreach ($col as $colKey => $colValue): ?>
                                                                                                <tr>
                                                                                                    <td class="onehundredtwenty"><?php echo $this->escape($colKey); ?></td>
                                                                                                    <td><?php echo $this->escape($colValue); ?></td>
                                                                                                </tr>
                                                                                            <?php endforeach; ?>
                                                                                        </table>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        <?php endforeach; ?>
                                                                    <?php else: ?>
                                                                        <?php echo $this->escape($tableValue); ?>
                                                                    <?php endif; ?>
                                                            </td>
                                                        </tr>   
                                                    <?php endforeach; ?>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <?php echo $this->escape($dbValue); ?>
                            <?php endif; ?>
                    </td>
                </tr>   
            <?php endforeach; ?>
        </table>
    <?php endforeach; ?>
</div>
