<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Account information for <?php echo $this->escape(Daiquiri_Auth::getInstance()->getCurrentUsername()); ?> </h2>

    <h4>Database status</h4>

    <?php if ($this->database['message'] !== false): ?>
    <p>
        <?php echo $this->escape($this->database['message']); ?>
    </p>
    <?php endif; ?>

    <?php if ($this->database['guest'] !== false): ?>
    <p>
        You are using the guest user. For a personal account, please sign up <?php echo $this->internalLink(array('text' => 'here', 'href' => '/auth/registration/register')); ?>.
    </p>
    <?php endif; ?>

    <?php if ($this->database['nactive'] !== false): ?>
    <p>
        Currently, there <?php echo (($this->database['nactive'] === 1) ? 'is ' : 'are ') . $this->escape($this->database['nactive']). (($this->database['nactive'] === 1) ? ' job' : ' jobs'); ?> in the queue.
    </p>
    <?php endif; ?>

    <p class="<?php echo (($this->database['quota']['exceeded'] === true) ? 'text-error' : '') ?>">
        <?php if ($this->database['guest'] === true): ?>
        The guest user is using <?php echo $this->escape($this->database['quota']['used']); ?> bytes of its quota of <?php echo $this->escape($this->database['quota']['max']); ?> bytes.
        <?php else: ?>
        You are using <?php echo $this->escape($this->database['quota']['used']); ?> bytes of your quota of <?php echo $this->escape($this->database['quota']['max']); ?> bytes.
        <?php endif; ?>
    </p>

    <h4>Job groups</h4>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Prev</th>
                <th>Next</th>
                <th>Hidden</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->groups as $group): ?>
            <tr>
                <?php foreach (array('id','name','prev_id','next_id','hidden') as $key): ?>
                <td>
                    <?php echo $this->escape($group[$key]); ?>
                </td>
                <?php endforeach; ?>
                <td>
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'Update',
                        'href' => '/query/account/update-group/id/' . $group['id'],
                        'append' => '&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'Move',
                        'href' => '/query/account/move-group/id/' . $group['id'],
                        'append' => '&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'Toggle',
                        'href' => '/query/account/toggle-group/id/' . $group['id'],
                        'append' => '&nbsp;'
                    ));
                    echo $this->internalLink(array(
                        'text' => 'Delete',
                        'href' => '/query/account/delete-group/id/' . $group['id']
                    ));
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <div class="row">
    <?php echo $this->internalLink(array(
        'text' => 'Create new group',
        'href' => '/query/account/create-group/',
        'prepend' => '<p class="daiquiri-widget span3">',
        'append' => '</p>'
    ));?>
    </div>

    <h4>Job list</h4>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Table</th>
                <th>Status</th>
                <th>Timestamp</th>
                <th>Group Id</th>
                <th>Prev</th>
                <th>Next</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->jobs as $job): ?>
            <tr>
                <td>
                    <?php echo $this->internalLink(array(
                        'href' => '/query/account/show-job/id/' . $job['id'],
                        'text' => $job['id']
                    )); ?>
                </td>
                <?php foreach (array('table','status','time','group_id','prev_id','next_id') as $key): ?>
                <td>
                    <?php echo $this->escape($job[$key]); ?>
                </td>
                <?php endforeach; ?>
                <td>
                    <?php
                    echo $this->internalLink(array(
                        'text' => 'Rename',
                        'href' => '/query/account/rename-job/id/' . $job['id'],
                        'append' => '&nbsp;'));
                    echo $this->internalLink(array(
                        'text' => 'Move',
                        'href' => '/query/account/move-job/id/' . $job['id'],
                        'append' => '&nbsp;'));
                    echo $this->internalLink(array(
                        'text' => 'Remove',
                        'href' => '/query/account/remove-job/id/' . $job['id'],
                        'append' => '&nbsp;'));
                    echo $this->internalLink(array(
                        'text' => 'Kill',
                        'href' => '/query/account/kill-job/id/' . $job['id']));
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
