<?php
/*
 *  Copyright (c) 2012-2014 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Jobs from <?php echo $this->escape(Daiquiri_Auth::getInstance()->getCurrentUsername()); ?> </h2>

    <?php if ($this->nactive !== false): ?>
    <p>Currently, there are <?php echo $this->escape($this->nactive); ?> jobs in the queue.</p>
    <?php endif; ?>

    <?php foreach ($this->jobs as $job): ?>
    <table class="table table-bordered">
        <?php foreach ($job as $key => $value): ?>
            <tr>
                <td class="onehundredfifty"><?php echo ucfirst($this->escape($key)); ?></td>
                <td><?php echo $this->escape($value); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php endforeach; ?>
</div>
