<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Native database functions</h2>

    <?php foreach ($this->native_functions as $row): ?>

    <h6><?php echo $this->escape($row['name']); ?></h6>

    <dl class="dl-horizontal">
        <?php foreach ($row as $key => $value): ?>
        <dt><?php echo $this->escape(ucfirst($key)); ?></dt>
        <dd><?php echo (empty($value) ? '&nbsp' : $this->escape($value)) ?></dd>
        <?php endforeach; ?>
    </dl>

    <?php endforeach; ?>
</div>
