<?php
/*
 *  Copyright (c) 2012, 2013 Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>, 
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Job details</h2>

    <table class='table table-bordered'>
        <?php foreach ($this->job as $element): ?>
            <tr>
                <td class="onehundredfifty"><?php echo $this->escape($element['name']); ?></td>
                <td>
                    <?php
                    if ($element['key'] === "query" || $element['key'] === "actualQuery") {
                        echo nl2br($this->escape($element['value']));
                    } else {
                        echo $this->escape($element['value']);
                    }
                    ?>
                </td>
            </tr>   
        <?php endforeach; ?>
    </table>
</div>
