<?php
/*
 *  Copyright (c) 2012-2015  Jochen S. Klar <jklar@aip.de>,
 *                           Adrian M. Partl <apartl@aip.de>,
 *                           AIP E-Science (www.aip.de)
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<div class="main">
    <h2>Details for job <?php echo $this->escape($this->job['table']); ?></h2>

    <h4>Query</h4>
    <pre><?php echo $this->escape($this->job['query']); ?></pre>

    <h4>Job parameters</h4>

    <dl class="dl-horizontal">
        <dt>Status</dt>
        <dd><?php echo $this->escape($this->job['status']); ?></dd>

        <?php if (!empty($this->job['error'])): ?>
        <dt>Error</dt>
        <dd><?php echo $this->escape($this->job['error']); ?></dd>
        <?php endif; ?>

        <dt>Full database table name</dt>
        <dd><?php echo $this->escape($this->job['database']); ?>.<?php echo $this->escape($this->job['table']); ?></dd>

        <dt>Internal job id</dt>
        <dd><?php echo $this->escape($this->job['id']); ?></dd>

        <dt>Time submitted</dt>
        <dd><?php echo $this->escape($this->job['time']); ?></dd>

        <?php if (isset($this->job['timeQueue'])): ?>
        <dt>Time in queue [s]</dt>
        <dd><?php echo $this->escape($this->job['timeQueue']); ?></dd>
        <?php endif; ?>

        <?php if (isset($this->job['timeQuery'])): ?>
        <dt>Time for query [s]</dt>
        <dd><?php echo $this->escape($this->job['timeQuery']); ?></dd>
        <?php endif; ?>

        <?php if (isset($this->job['nrows'])): ?>
        <dt>Number of rows</dt>
        <dd><?php echo $this->escape($this->job['nrows']); ?></dd>
        <?php endif; ?>

        <?php if (isset($this->job['size'])): ?>
        <dt>Size of the table in bytes</dt>
        <dd><?php echo $this->escape($this->job['size']); ?></dd>
        <?php endif; ?>
    </dl>

    <h4>Additional infomation</h4>

    <dl class="dl-horizontal">
        <?php foreach ($this->job['additional'] as $element): ?>
        <dt><?php echo $this->escape($element['name']); ?></dt>
        <dd><?php echo $this->escape($element['value']); ?></dd>
        <?php endforeach; ?>
    </dl>

    <?php if (isset($this->job['plan'])): ?>
    <h4>Query plan</h4>
    <pre><?php echo $this->escape($this->job['plan']); ?></pre>
    <?php endif; ?>

    <?php if (isset($this->job['actualQuery'])): ?>
    <h4>Actual Query</h4>
    <pre><?php echo $this->escape($this->job['actualQuery']); ?></pre>
    <?php endif; ?>
</div>
